import kotlinx.kover.gradle.plugin.dsl.CoverageUnit
import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeSimulatorTest

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
    // Coverage measurement (capability `coverage-bounds`). Applied here rather than in a
    // `subprojects {}` block so the instrumented set is readable per module.
    alias(libs.plugins.kover)
}
// Coverage (capability `coverage-bounds`). The report is filtered to this module's OWN classes.
// The crediting edge that lets `:adapter:generic:fake`'s feature tests count toward this module is
// declared in the ROOT build file, not here: `ModuleSetTest` asserts this file names no module at
// all, because that absence is the precondition for the platform-free compile error.
kover {
    reports {
        filters {
            includes {
                projects.add(":domain:model")
            }
        }
    }
}


// Full failure messages in CI: the Kotlin/Native simulator runner otherwise prints a terse
// "AssertionError at null:-1" with no expected/actual.
tasks.withType<KotlinNativeSimulatorTest>().configureEach {
    testLogging {
        exceptionFormat = TestExceptionFormat.FULL
        showStandardStreams = true
    }
}

// The core'"'"'s `model` zone (spec `module-architecture`, "The module set withholds; packages organize").
// The vocabulary, pure codecs and domain services. References nothing project-internal.
//
// Zone edges are declared with `implementation()`, never `api()`: a zone must not leak to a downstream
// consumer transitively. A consumer that needs another zone declares it.
// NO iosMain source directory, ever — the targets exist so iosMain elsewhere can compile against this.

// The event link's origin, generated from the RESOLVED DEPLOYMENT (capability
// `deployment-configuration`) so the app, the backend, the xcconfig and the site all derive it from one
// declared value rather than each holding a copy. `snapsync.deployment` names WHICH deployment; the
// resolver renders it to `build/deployment.properties`, which Gradle reads natively.
//
// The resolver is invoked here at CONFIGURATION time because `LINK_ORIGIN` is generated into a source
// set. It is stdlib-only Python — the one runtime present on every runner and dev machine that also has
// Gradle (no CI job carries both Deno and Gradle, so the backend's runtime could not be the resolver).
val deploymentName: String = providers.gradleProperty("snapsync.deployment").get()

val resolvedDeployment: Map<String, String> = run {
    val repoRoot = rootProject.layout.projectDirectory.asFile
    providers.exec {
        workingDir(repoRoot)
        commandLine("python3", "scripts/resolve-deployment.py", deploymentName, "--quiet")
    }.result.get().assertNormalExitValue()
    val rendered = repoRoot.resolve("build/deployment.properties")
    check(rendered.isFile) { "the resolver produced no ${rendered.path} — cannot generate LINK_ORIGIN" }
    rendered.readLines()
        .filterNot { it.isBlank() || it.startsWith("#") }
        .associate { line -> line.substringBefore('=') to line.substringAfter('=') }
}

val linkDomain: String = requireNotNull(resolvedDeployment["domain"]) {
    "deployment '$deploymentName' resolved no `domain` — the event link has no origin"
}

// ⚠️ The scheme is UNCONDITIONALLY `https`, and that is NOT an oversight to be "fixed" into agreement
// with the upload base, which derives `http` for a loopback host (`upload_scheme`, the resolver). The two
// are asymmetric because the platform rules behind them are different, and only one has an exemption:
//   * the UPLOAD BASE is an ordinary network request, governed by ATS — which exempts the loopback IP
//     literal, which is the only reason a simulator can reach `deno task dev:local` over plain HTTP.
//   * LINK_ORIGIN is a UNIVERSAL LINK origin. `applinks:` and the AASA are HTTPS-only by Apple's
//     contract (capability `event-link`: "the HTTPS Universal Link"); iOS will not claim an `http://`
//     link at all, so deriving a scheme here would generate a constant that cannot work.
// A local deployment therefore gets an https LINK_ORIGIN it never exercises — correct and inert — rather
// than an http one that would look consistent and mean nothing.
val generateLinkOrigin by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/linkOrigin/kotlin")
    val domain = linkDomain
    inputs.property("domain", domain)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().asFile.resolve("app/snapsync/model/LinkOrigin.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            // GENERATED by :domain's generateLinkOrigin task — do not edit.
            // Source of truth: the resolved deployment (see deployments/ and scripts/resolve-deployment.py).
            package app.snapsync.model

            /**
             * The event link's canonical origin (capability `event-link`). Both halves of the codec are
             * anchored here: [encodeEventUrl] emits it and [decodeEventUrl] matches it, so producer and
             * consumer cannot drift.
             */
            public const val LINK_ORIGIN: String = "https://$domain"

            """.trimIndent(),
        )
    }
}

kotlin {
    jvmToolchain(libs.versions.jdk.get().toInt())
    jvm()
    iosArm64()
    iosSimulatorArm64()
    sourceSets {
        commonMain.configure { kotlin.srcDir(generateLinkOrigin) }
        commonMain.dependencies {
            // The per-zone library allowlist (spec `module-architecture`, "Core purity is closed by
            // default"): coroutines (StateFlow/Flow port shapes), serialization + datetime (the
            // config/manifest vocabulary and cutoff codecs), kermit (the engine's diagnostics).
            api(libs.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kermit)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.coroutines.test)
        }
    }
}

// ---- Coverage bounds (capability `coverage-bounds`) ---------------------------------------------
//
// A FLOOR on this module's coverage, seeded at what the tree measured when the gate landed, and
// permitted to move in one direction only: UP. The destination is full coverage, and these numbers
// are the distance still to travel.
//
// RAISING a bound is ordinary work - do it in the change that makes it true. LOWERING one requires a
// stated forcing proof in that change's description, naming what makes the loss of coverage
// unavoidable. Nothing checks this: it is a ratchet carried by this paragraph and by review, and it
// is deliberately NOT a proof. `complexity-budgets` carries the same contract at the opposite
// polarity - a ceiling that may only fall.
//
// TWO RULES, because they fail on different things. The aggregate catches a broad slide that leaves
// every package above the floor; the PACKAGE FLOOR - "no package here is worse than this" - catches
// one package rotting behind well-tested neighbours, which is the shape an untested class has.
//
// ENGINE: Kover's default, not JaCoCo. The two disagree by up to 26% on a single package's
// denominator, so every number below is engine-specific and switching engines means re-seeding all
// of them in that same change.
//
// Bounds are whole percentages (`minValue` is an `Int`), so each concedes up to 1% of its scope.
//
// ONE package now, so there is no floor rule here: the aggregate IS the floor. The old
// `:domain package floor` measured eleven packages inside a single `:domain` module; the zone split
// turned each of those zones into a module with an aggregate of its own, which is the same check
// expressed by the module graph instead of by a grouping rule. `:domain:compose` is the one zone with
// no bound at all - a composition root is outside the measurable set (capability `coverage-bounds`),
// and leaving the module uninstrumented states that better than the package exclude that used to.
//
// What remains uncovered is largely NOT a testing gap: data-class `equals`/`hashCode`/`toString` and
// enum `<clinit>` make up the bulk - 72 of `LedgerEntry`'s 86 missed instructions are `equals` alone -
// and no test reaches them meaningfully.
//
// A zero on a method can mean MISPLACED rather than untested. `SyncEngine.complete` read zero while
// `SyncEngineTest` covered it from `:test:world`, whose instrumentation is off and which credits
// nothing. Before writing a test for an uncovered method, grep for one - a duplicate written to move a
// number is worse than the gap it closes.
kover {
    reports {
        total {
            verify {
                onCheck = true
                rule(":domain:model aggregate") {
                    bound {
                        minValue = 85
                        coverageUnits = CoverageUnit.INSTRUCTION
                    }
                    bound {
                        minValue = 80
                        coverageUnits = CoverageUnit.BRANCH
                    }
                }
            }
        }
    }
}
