plugins {
    alias(libs.plugins.kotlin.multiplatform)
    // The allowed targets, declared once (`docs/architecture.md`, "Zones inside the core").
    id("snapsync.targets")
    alias(libs.plugins.kotlin.serialization)
    // The zero coverage gate (`docs/architecture.md`, "Coverage"): no instruction and no branch missed.
    id("snapsync.coverage-zero")
    // The simulator test run's standard streams, beside its failure messages.
    id("snapsync.simulator-test-output")
}

// The core'"'"'s `model` zone (`docs/architecture.md`, "The module set withholds; packages organize").
// The vocabulary, pure codecs and domain services. References nothing project-internal.
//
// Zone edges are declared with `implementation()`, never `api()`: a zone must not leak to a downstream
// consumer transitively. A consumer that needs another zone declares it.
// NO iosMain source directory, ever — the targets exist so iosMain elsewhere can compile against this.

// The event link's origin, generated from the RESOLVED DEPLOYMENT (capability
// `docs/deployment.md`) so the app, the backend, the xcconfig and the site all derive it from one
// declared value rather than each holding a copy. `snapsync.deployment` names WHICH deployment; the
// resolver renders it to `build/deployment.properties`, which Gradle reads natively.
//
// The resolver is invoked here at CONFIGURATION time because `LINK_ORIGIN` is generated into a source
// set. It is stdlib-only Python — the one runtime present on every runner and dev machine that also has
// Gradle (no CI job carries both Deno and Gradle, so the backend's runtime could not be the resolver).
val deploymentName: String = providers.gradleProperty("snapsync.deployment").get()

val resolvedDeployment: Map<String, String> = run {
    val repoRoot = rootProject.layout.projectDirectory.asFile
    providers.exec {
        workingDir(repoRoot)
        commandLine("python3", "scripts/resolve-deployment.py", deploymentName, "--quiet")
    }.result.get().assertNormalExitValue()
    val rendered = repoRoot.resolve("build/deployment.properties")
    check(rendered.isFile) { "the resolver produced no ${rendered.path} — cannot generate LINK_ORIGIN" }
    rendered.readLines()
        .filterNot { it.isBlank() || it.startsWith("#") }
        .associate { line -> line.substringBefore('=') to line.substringAfter('=') }
}

val linkDomain: String = requireNotNull(resolvedDeployment["domain"]) {
    "deployment '$deploymentName' resolved no `domain` — the event link has no origin"
}

// ⚠️ The scheme is UNCONDITIONALLY `https`, and that is NOT an oversight to be "fixed" into agreement
// with the upload base, which derives `http` for a loopback host (`upload_scheme`, the resolver). The two
// are asymmetric because the platform rules behind them are different, and only one has an exemption:
//   * the UPLOAD BASE is an ordinary network request, governed by ATS — which exempts the loopback IP
//     literal, which is the only reason a simulator can reach `deno task dev:local` over plain HTTP.
//   * LINK_ORIGIN is a UNIVERSAL LINK origin. `applinks:` and the AASA are HTTPS-only by Apple's
//     contract (capability `join-event`: "the HTTPS Universal Link"); iOS will not claim an `http://`
//     link at all, so deriving a scheme here would generate a constant that cannot work.
// A local deployment therefore gets an https LINK_ORIGIN it never exercises — correct and inert — rather
// than an http one that would look consistent and mean nothing.
val generateLinkOrigin = tasks.register("generateLinkOrigin") {
    val outDir = layout.buildDirectory.dir("generated/linkOrigin/kotlin")
    val domain = linkDomain
    inputs.property("domain", domain)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().asFile.resolve("app/snapsync/model/LinkOrigin.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            // GENERATED by :domain's generateLinkOrigin task — do not edit.
            // Source of truth: the resolved deployment (see deployments/ and scripts/resolve-deployment.py).
            package app.snapsync.model

            /**
             * The event link's canonical origin (capability `join-event`). Both halves of the codec are
             * anchored here: [encodeEventUrl] emits it and [decodeEventUrl] matches it, so producer and
             * consumer cannot drift.
             */
            public const val LINK_ORIGIN: String = "https://$domain"

            """.trimIndent(),
        )
    }
}

// The longest event window the backend accepts, generated from the SAME resolved deployment the backend
// is bundled with (`eventWindowMaxSeconds`, `deployments/components/policy.json`). The create screen bounds
// its range picker to it (capability `create-event`), so the limit the host meets and the limit
// `POST /events` enforces are one declared value — not a client mirror that could drift into a refusal
// the screen has no words for.
val eventWindowMaxSeconds: Long = requireNotNull(resolvedDeployment["eventWindowMaxSeconds"]?.toLongOrNull()) {
    "deployment '$deploymentName' resolved no numeric `eventWindowMaxSeconds` — the create picker has no bound"
}

val generateEventWindowMax = tasks.register("generateEventWindowMax") {
    val outDir = layout.buildDirectory.dir("generated/eventWindowMax/kotlin")
    val seconds = eventWindowMaxSeconds
    inputs.property("eventWindowMaxSeconds", seconds)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().asFile.resolve("app/snapsync/model/EventWindowMax.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            // GENERATED by :domain's generateEventWindowMax task — do not edit.
            // Source of truth: the resolved deployment's `eventWindowMaxSeconds` (see deployments/ and
            // scripts/resolve-deployment.py) — the value the backend validates `endsAt - startsAt` against.
            package app.snapsync.model

            /**
             * The longest event window, `endsAt - startsAt`, the backend accepts, in seconds (capability
             * `create-event`). The create screen's picker cannot produce a longer range.
             */
            public const val EVENT_WINDOW_MAX_SECONDS: Long = ${seconds}L

            """.trimIndent(),
        )
    }
}

kotlin {
    sourceSets {
        commonMain.configure {
            kotlin.srcDir(generateLinkOrigin)
            kotlin.srcDir(generateEventWindowMax)
        }
        commonMain.dependencies {
            // The per-zone library allowlist (`docs/architecture.md`, "Core purity is closed by
            // default"): coroutines (StateFlow/Flow port shapes), serialization + datetime (the
            // config/manifest vocabulary and cutoff codecs), kermit (the engine's diagnostics).
            api(libs.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kermit)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.coroutines.test)
        }
    }
}

// Coverage (`docs/architecture.md`): at zero, under `snapsync.coverage-zero`. The crediting edges that let
// `:adapter:generic:mock`'s and `:test:feature`'s tests count toward this module are declared in the ROOT build file,
// not here: `ModuleSetTest` asserts this file names no module at all, because that absence is the precondition for the
// platform-free compile error. What the gate excuses here is the serialization plugin's zero-mask missing-field check
// in the `@Serializable` classes whose every field has a default; the task prints each one.
