package app.snapsync.architecture

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

/**
 * **The event link's domain agrees everywhere it appears** (capability `architecture-guards`).
 *
 * This guard has SHRUNK. The domain used to live in nine places across four toolchains — six of them
 * pinned by nothing, including `BACKGROUND_UPLOAD_URL_BASE`, the device-facing upload host itself — and
 * this test asserted agreement across four hand-written literals. It now lives in ONE declared
 * deployment (capability `deployment-configuration`), from which every copy is GENERATED:
 *
 * 1. `LINK_ORIGIN` — generated by `:domain`'s `generateLinkOrigin` task from the resolved deployment,
 * 2. `Deployment.xcconfig` → `ASSOCIATED_DOMAIN` and `Deployment.plist` → `uploadBase` — both rendered
 *    by `scripts/resolve-deployment.py` from the one resolution. The upload host lives in the PLIST
 *    because it carries a scheme, and `//` opens a comment in the xcconfig grammar,
 * 3. `iosApp.entitlements`, which must reference the build setting rather than hard-code a host,
 * 4. the backend's AASA and the site's canonical URLs — both read the same rendering.
 *
 * The previous version of this requirement asserted that the backend's copy **could not** be
 * single-sourced ("generating it would couple two deliberately independent pipelines"). That was true
 * only while the two pipelines had no shared input; a declared deployment IS one, so agreement is now
 * CONSTRUCTED rather than checked. Guards are opt-in and cover what someone remembered — which is why
 * the upload host went unpinned for so long. Generation is total.
 *
 * What remains here is a STALENESS check: the generated artefacts must match the deployment they derive
 * from. It still fails loudly rather than vacuously — a moved or renamed file fails the test rather than
 * silently scanning nothing.
 *
 * Why a test rather than review: drift here **raises nothing**. A stale entitlement or a mismatched AASA
 * does not fail a build, log a warning, or throw at runtime — iOS simply declines to match the link, and
 * every invite quietly opens a browser instead of the app. From the outside that is indistinguishable
 * from a recipient who never installed SnapSync, which is exactly the failure this whole capability
 * exists to remove.
 */
class EventLinkDomainTest {

    private val repoRoot: File = generateSequence(File(".").absoluteFile) { it.parentFile }
        .firstOrNull { File(it, "settings.gradle.kts").isFile }
        ?: fail("could not locate the repository root")

    private fun read(relative: String): String {
        val file = File(repoRoot, relative)
        assertTrue(file.isFile, "guard is scanning nothing — $relative not found from $repoRoot")
        return file.readText()
    }

    /** The one source: the deployment this build resolved, rendered by the resolver. */
    private val domain: String = Regex("""^domain=(.+)$""", RegexOption.MULTILINE)
        .find(read("build/deployment.properties"))?.groupValues?.get(1)?.trim()
        ?: fail(
            "build/deployment.properties declares no `domain` — run " +
                "`python3 scripts/resolve-deployment.py <deployment>`; the renderings are generated, " +
                "never committed",
        )

    @Test
    fun `the backend takes its domain from the resolved deployment, never from a literal`() {
        val backend = read("api/src/config.ts")
        // THE FINAL LABEL MUST CONTAIN A LETTER, which is what separates a hostname from every other
        // dotted literal. Without that the pattern reads `= "0.1"` — a two-part app version — as a host
        // whose TLD is `1`, and refuses a value that could not name a machine: a public suffix is never
        // all-digits, or an IPv4 address would be ambiguous with one. The looser form failed the first
        // ordinary decimal anyone put in this file (`MIN_APP_VERSION`, capability `min-app-version`).
        //
        // Narrowing here rather than exempting the constant: an exemption would have to be renewed by
        // every future version, port or ratio, and each renewal is a chance to wave through the literal
        // this guard exists to catch.
        assertTrue(
            !Regex("""=\s*"[a-z0-9-]+(\.[a-z0-9-]+)*\.[a-z][a-z0-9-]*"""").containsMatchIn(backend),
            "api/src/config.ts contains a hostname literal. The domain is supplied by the resolved " +
                "deployment now; a literal here is a copy nothing checks, which is how " +
                "BACKGROUND_UPLOAD_URL_BASE went unpinned.",
        )
        assertTrue(
            backend.contains("linkDomain: d.domain"),
            "api/src/config.ts no longer derives `linkDomain` from the resolved deployment — the AASA " +
                "would serve for a host nothing else agrees with, silently.",
        )
    }

    // REMOVED: `the generated xcconfig fragment matches the deployment it derives from`.
    //
    // It could not fail. `domain/model/build.gradle.kts` runs `scripts/resolve-deployment.py` during the
    // build, regenerating `Deployment.xcconfig` and `Deployment.plist` from the resolved deployment
    // immediately BEFORE this guard reads them — so the artifact and the deployment were re-derived from
    // one source moments earlier and staleness had already been eliminated. Measured: editing
    // ASSOCIATED_DOMAIN by hand and re-running left the guard green, because the edit was overwritten.
    //
    // Both of its assertions (the xcconfig's ASSOCIATED_DOMAIN, the plist's uploadBase) compared
    // generated against generated. A check that cannot fail is not a guard, and stating it as one
    // overstates what the build proves. The seven assertions that remain inspect COMMITTED artifacts —
    // literals, the entitlement's build-setting reference, the retired URL scheme — where drift is real.

    @Test
    fun `the committed xcconfig holds no value the fragment owns`() {
        val committed = read("iosApp/Configuration/Config.xcconfig")
        assertTrue(
            committed.contains("#include \"Deployment.xcconfig\""),
            "Config.xcconfig no longer includes the generated fragment — every value it owns would " +
                "silently fall back to whatever remains committed.",
        )
        for (setting in listOf(
            "ASSOCIATED_DOMAIN",
            "BACKGROUND_UPLOAD_URL_BASE",
            "BUNDLE_ID",
            "TEAM_ID",
            "APS_ENVIRONMENT",
            "APNS_ENV",
            "SENTRY_DSN",
        )) {
            assertTrue(
                !Regex("""^$setting = """, RegexOption.MULTILINE).containsMatchIn(committed),
                "Config.xcconfig re-declares `$setting`, which the generated fragment owns. A committed " +
                    "copy is exactly the unchecked literal this change removed.",
            )
        }
    }

    @Test
    fun `no value the app reads is declared as an xcconfig build setting`() {
        // The four values the two processes READ live in Deployment.plist, not the fragment. Re-adding
        // one here would put a scheme-carrying string back into a grammar where `//` opens a comment
        // and there is no escape — which truncated the crash-reporting DSN to `https:`, non-empty, so
        // the SDK never started while the bug-report dialog kept opening and losing every dump.
        val fragment = read("iosApp/Configuration/Deployment.xcconfig")
        for (setting in listOf("BACKGROUND_UPLOAD_URL_BASE", "APNS_ENV", "SENTRY_DSN", "SENTRY_ENVIRONMENT")) {
            assertTrue(
                !Regex("""^$setting = """, RegexOption.MULTILINE).containsMatchIn(fragment),
                "Deployment.xcconfig declares `$setting`. Values the app reads belong in " +
                    "Deployment.plist, which escapes; this grammar does not.",
            )
        }
        for (line in fragment.lines()) {
            if (line.startsWith("//") || " = " !in line) continue
            val (name, value) = line.split(" = ", limit = 2)
            assertTrue(
                "//" !in value,
                "`$name` carries `//`, which opens an xcconfig comment: the built value would be " +
                    "truncated at that point, silently.",
            )
        }
    }

    @Test
    fun `the app entitlement takes its domain from the build setting, not a literal`() {
        val entitlements = read("iosApp/iosApp/iosApp.entitlements")
        assertTrue(
            entitlements.contains("com.apple.developer.associated-domains"),
            "iosApp.entitlements declares no associated-domains entitlement — the app cannot claim the " +
                "event link at all, and every invite opens a browser.",
        )
        assertTrue(
            entitlements.contains("\$(ASSOCIATED_DOMAIN)"),
            "iosApp.entitlements hard-codes its associated domain instead of taking " +
                "\$(ASSOCIATED_DOMAIN) from the generated Deployment.xcconfig, re-opening the drift " +
                "this guard closes.",
        )
    }

    @Test
    fun `the extension claims no associated domain`() {
        val extension = read("iosApp/BackgroundUploadExtension/BackgroundUploadExtension.entitlements")
        assertTrue(
            !extension.contains("com.apple.developer.associated-domains"),
            "the background-upload extension declares an associated domain. It never handles URLs; " +
                "claiming one only widens what must be provisioned and kept in agreement.",
        )
    }

    @Test
    fun `the custom URL scheme stays retired`() {
        val infoPlist = read("iosApp/iosApp/Info.plist")
        // Match the plist KEY, not the word: the file names `CFBundleURLTypes` in a comment explaining
        // why it is absent, and a bare substring check cannot tell prose from a declaration.
        assertTrue(
            !infoPlist.contains("<key>CFBundleURLTypes</key>"),
            "Info.plist re-registers a custom URL scheme. The `snapsync://` scheme is retired " +
                "(capability `event-link`): the one authoritative codec no longer accepts it, so a " +
                "scheme registered here would route links the app cannot decode.",
        )
    }

    /** Fail loudly rather than vacuously: if the files moved, this guard is inspecting nothing. */
    @Test
    fun `the guard actually found the files it inspects`() {
        assertTrue(domain.isNotBlank(), "resolved an empty event-link domain — the guard proves nothing")
        assertTrue(read("api/src/config.ts").contains("linkDomain"))
        assertTrue(read("iosApp/Configuration/Deployment.xcconfig").contains("ASSOCIATED_DOMAIN"))
        assertTrue(read("iosApp/iosApp/iosApp.entitlements").contains("application-groups"))
        assertTrue(read("iosApp/Configuration/Deployment.plist").contains("<key>apnsEnv</key>"))
        // The app's Info.plist must NOT carry deployment values any more; assert it is being read at
        // all through a key Apple owns, so this twin still fails when the file moves.
        assertTrue(read("iosApp/iosApp/Info.plist").contains("CFBundleIdentifier"))
    }
}
