package app.snapsync.buildlogic

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.provider.Property
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension

/**
 * The port-contract arrangement both iOS adapter modules share (`docs/architecture.md`, "A build-time-only module is
 * contained by compilation"; `docs/testing.md`, the recorded hosts):
 *
 *  - `src/rig/kotlin` compiles into `iosMain` under `-Psnapsync.rig=true` ([RigPlugin], applied here) and into `iosTest`
 *    otherwise, so a production build contains none of it and every build still compile-checks it;
 *  - `embedContractRecordings` embeds the committed `.rec` recordings (`test/contracts/recordings`) into `iosTest` as
 *    Kotlin constants, so the simulator test executable needs no path into the repository and the `.rec` files stay
 *    the single source. Each module needs its own copy: the generated map is `internal` to the test compilation it
 *    lands in, so the module names the package it lands in (`contractRecordings { packageName = "…" }`).
 *
 * What the rig source set DEPENDS on differs per module and stays in each build file, under `if (rigEnabled)`.
 */
class IosRigSourcesPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        project.pluginManager.apply(RigPlugin::class.java)
        val rigEnabled = project.rigEnabled
        val recordings = project.extensions.create("contractRecordings", ContractRecordings::class.java)

        val sources = project.fileTree(project.rootProject.layout.projectDirectory.dir("test/contracts/recordings")) {
            include("*.rec")
        }
        val out = project.layout.buildDirectory.dir("generated/contractRecordings/kotlin")
        val packageName = recordings.packageName
        val taskPath = "${project.path}:embedContractRecordings"
        val embed = project.tasks.register("embedContractRecordings") {
            inputs.files(sources)
            inputs.property("packageName", packageName)
            outputs.dir(out)
            doLast {
                val entries = sources.files.sortedBy { it.name }.joinToString("") { f ->
                    val text = f.readText()
                    check("\"\"\"" !in text) { "${f.name} contains a triple quote and cannot be embedded" }
                    "    \"${f.nameWithoutExtension}\" to \"\"\"" + text.replace("$", "\${'$'}") + "\"\"\",\n"
                }
                val pkg = packageName.get()
                val file = out.get().file(pkg.replace('.', '/') + "/Recordings.kt").asFile
                file.parentFile.mkdirs()
                file.writeText(
                    "package $pkg\n\n" +
                        "// GENERATED by $taskPath from test/contracts/recordings/*.rec\n" +
                        "internal val RECORDINGS: Map<String, String> = mapOf(\n" + entries + ")\n",
                )
            }
        }

        project.pluginManager.withPlugin("org.jetbrains.kotlin.multiplatform") {
            // `iosMain`/`iosTest` are created by the hierarchy template once the module declares its targets, so the
            // switch is attached to whichever of them appears, whenever it does.
            project.extensions.getByType(KotlinMultiplatformExtension::class.java).sourceSets.configureEach {
                when (name) {
                    "iosMain" -> if (rigEnabled) kotlin.srcDir("src/rig/kotlin")
                    "iosTest" -> {
                        if (!rigEnabled) kotlin.srcDir("src/rig/kotlin")
                        kotlin.srcDir(embed)
                    }
                }
            }
        }
    }
}

/** Where a module's embedded recordings land: the package its replay tests read `RECORDINGS` from. */
abstract class ContractRecordings {
    abstract val packageName: Property<String>
}
