package app.snapsync.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Generates, for every SQLDelight `*Queries` class under [generatedCode], one call per statement with a typed
 * fixture for each argument — the statement list `DatabasesContract`'s schema clauses run on every platform's
 * SQLite (`docs/testing.md`, "Every statement runs on every SQLite").
 *
 * The list is READ from SQLDelight's own output, never written by hand, so a query added to a `.sq` file joins the
 * clauses with nothing to remember. Nothing is skipped silently either: an argument type with no fixture in
 * [fixtures], or a `public fun` the parser cannot place, fails the generation naming it.
 *
 * Each `*Queries` class becomes an object `<Name>Statements` in [packageName] holding its READS (a `Query`, run to
 * the end) and its WRITES (a `QueryResult<Long>`), split because the clause runs every write in a transaction it
 * rolls back — a plain `INSERT` run twice under one key would otherwise trip the primary key, which says nothing
 * about the platform.
 */
abstract class SchemaStatementsTask : DefaultTask() {

    /** SQLDelight's generated code root (`build/generated/sqldelight/code` of the module that owns the schemas). */
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val generatedCode: DirectoryProperty

    /** Where the statement objects are written: a Kotlin source root. */
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    /** The package the statement objects are generated into. */
    @get:Input
    abstract val packageName: Property<String>

    /**
     * A Kotlin expression per argument type's simple name (`String` -> `"f"`). A nullable or collection argument
     * is derived from its element's fixture: a nullable one is given a VALUE, so the binding is exercised.
     */
    @get:Input
    abstract val fixtures: MapProperty<String, String>

    @TaskAction
    fun generate() {
        val sources = generatedCode.get().asFile.walkTopDown().filter { it.name.endsWith("Queries.kt") }.toList()
        if (sources.isEmpty()) throw GradleException("no *Queries.kt under ${generatedCode.get().asFile}")
        val out = outputDir.get().asFile.also { it.deleteRecursively() }
        val target = File(out, packageName.get().replace('.', '/')).also { it.mkdirs() }
        sources.forEach { source ->
            val queries = parseQueries(source.readText(), source.name)
            File(target, "${queries.className.removeSuffix("Queries")}Statements.kt").writeText(render(queries))
        }
    }

    private fun render(q: ParsedQueries): String {
        val name = q.className.removeSuffix("Queries") + "Statements"
        val used = q.statements.flatMap { s -> s.params.map { baseType(it.type) } }.toSet()
        val imports = (listOf("${q.packageName}.${q.className}") +
            q.imports.filter { it.substringAfterLast('.') in used }).sorted()
        fun calls(of: List<ParsedStatement>, run: String) = of.joinToString("") { s ->
            val args = s.params.joinToString(", ") { fixture(it.type, s.name) }
            "        SchemaStatement(\"${s.name.trim('`')}\") { it.${s.name}($args)$run },\n"
        }
        return buildString {
            append("// GENERATED by :test:contracts' generateSchemaStatements from ${q.className} — do not edit.\n")
            append("package ${packageName.get()}\n\n")
            imports.forEach { append("import $it\n") }
            append("\n/** Every statement of [${q.className}], with typed fixtures. */\n")
            append("internal object $name : SchemaStatements<${q.className}> {\n")
            append("    override val reads: List<SchemaStatement<${q.className}>> = listOf(\n")
            append(calls(q.statements.filter { !it.isWrite }, ".executeAsList()"))
            append("    )\n")
            append("    override val writes: List<SchemaStatement<${q.className}>> = listOf(\n")
            append(calls(q.statements.filter { it.isWrite }, ".value"))
            append("    )\n}\n")
        }
    }

    private fun baseType(type: String): String =
        type.removeSuffix("?").removePrefix("Collection<").removeSuffix(">")

    private fun fixture(type: String, statement: String): String {
        val collection = type.startsWith("Collection<")
        val element = baseType(type)
        val value = fixtures.get()[element]
            ?: throw GradleException(
                "$statement takes a `$element`, which has no fixture: add one to generateSchemaStatements' fixtures",
            )
        return if (collection) "listOf($value)" else value
    }
}

/** One parsed `*Queries` class. */
internal class ParsedQueries(
    val packageName: String,
    val className: String,
    val imports: List<String>,
    val statements: List<ParsedStatement>,
)

internal class ParsedStatement(val name: String, val params: List<ParsedParam>, val isWrite: Boolean)

internal class ParsedParam(val name: String, val type: String)

private val PACKAGE = Regex("""^package\s+([\w.]+)""", RegexOption.MULTILINE)
private val IMPORT = Regex("""^import\s+([\w.]+)$""", RegexOption.MULTILINE)
private val CLASS = Regex("""public class (\w+Queries)\(""")
private val FUN = Regex("""public fun (<[^>]+> )?(`?\w+`?)\(""")

/**
 * Parses SQLDelight's generated `*Queries` source. Every `public fun` is one of three shapes: a READ answering a
 * `Query<…>` / `ExecutableQuery<…>`, a WRITE answering `QueryResult<Long>`, or a READ's generic overload taking a
 * `mapper`, which repeats a read already listed. Anything else fails, so a new SQLDelight shape is noticed.
 */
internal fun parseQueries(text: String, file: String): ParsedQueries {
    val pkg = PACKAGE.find(text)?.groupValues?.get(1) ?: throw GradleException("$file: no package")
    val cls = CLASS.find(text)?.groupValues?.get(1) ?: throw GradleException("$file: no *Queries class")
    val statements = FUN.findAll(text).mapNotNull { match -> parseFun(text, match, file) }.toList()
    if (statements.isEmpty()) throw GradleException("$file: no statements found — has SQLDelight's output changed?")
    return ParsedQueries(pkg, cls, IMPORT.findAll(text).map { it.groupValues[1] }.toList(), statements)
}

private fun parseFun(text: String, match: MatchResult, file: String): ParsedStatement? {
    val name = match.groupValues[2]
    val open = match.range.last
    val close = closingParen(text, open)
    val params = splitTopLevel(text.substring(open + 1, close)).map { raw ->
        val (pName, pType) = raw.split(':', limit = 2).map(String::trim)
        ParsedParam(pName, pType)
    }
    val returns = text.substring(close + 1).trimStart().removePrefix(":").trimStart()
        .takeWhile { !it.isWhitespace() }.removeSuffix("{")
    return when {
        params.any { it.name == "mapper" } -> null
        returns.startsWith("Query<") || returns.startsWith("ExecutableQuery<") -> ParsedStatement(name, params, false)
        returns == "QueryResult<Long>" -> ParsedStatement(name, params, true)
        else -> throw GradleException("$file: `$name` answers `$returns`, a shape generateSchemaStatements does not know")
    }
}

private fun closingParen(text: String, open: Int): Int {
    var depth = 0
    for (i in open until text.length) {
        when (text[i]) {
            '(' -> depth++
            ')' -> if (--depth == 0) return i
        }
    }
    throw GradleException("unbalanced parameter list at $open")
}

private fun splitTopLevel(params: String): List<String> {
    val parts = mutableListOf<String>()
    var depth = 0
    val current = StringBuilder()
    for ((i, c) in params.withIndex()) {
        when {
            c == '(' || c == '<' -> depth++
            c == ')' -> depth--
            // A lambda type's arrow (`(T) -> R`, a mapper's) closes nothing.
            c == '>' && params.getOrNull(i - 1) != '-' -> depth--
        }
        if (c == ',' && depth == 0) {
            parts += current.toString()
            current.clear()
        } else {
            current.append(c)
        }
    }
    parts += current.toString()
    return parts.map(String::trim).filter(String::isNotEmpty)
}
