ASC_KEY_ID: snap-sync/appstore-connect/key-id
ASC_ISSUER_ID: snap-sync/appstore-connect/issuer-id
ASC_AUTH_KEY: snap-sync/appstore-connect/auth-key
BUNNY_API_KEY: snap-sync/bunny/api-key
BUNNY_STORAGE_ACCESS_KEY: snap-sync/bunny/storage-access-key
BUNNY_SCRIPT_DEPLOYMENT_KEY: snap-sync/bunny/script-deployment-key
BUNNY_DB_URL: snap-sync/bunny/db-url
BUNNY_DB_FULL_ACCESS_TOKEN: snap-sync/bunny/db-full-access-token
BUNNY_DB_READONLY_TOKEN: snap-sync/bunny/db-readonly-token
ADMIN_NOTIFY_KEY: snap-sync/admin/notify
BUGSINK_TOKEN: Personal/steho.bugsink.com/token
