package app.snapsync.contracts

import app.cash.sqldelight.ColumnAdapter
import app.cash.sqldelight.EnumColumnAdapter
import app.cash.sqldelight.Transacter
import app.cash.sqldelight.db.AfterVersion
import app.cash.sqldelight.db.QueryResult
import app.cash.sqldelight.db.SqlDriver
import app.cash.sqldelight.db.SqlSchema
import app.snapsync.model.AssetId
import app.snapsync.ports.Databases
import app.snapsync.ports.DbOpen
import app.snapsync.services.downloads.db.DownloadAsset
import app.snapsync.services.downloads.db.DownloadDatabase
import app.snapsync.services.downloads.db.DownloadResource
import app.snapsync.services.ledger.db.LedgerDatabase
import app.snapsync.services.ledger.db.LedgerRow
import kotlin.test.assertEquals
import kotlin.test.assertIs

/** One statement of a schema, run against its generated queries with fixed arguments. */
class SchemaStatement<Q>(val name: String, val run: (Q) -> Unit)

/** Every statement of one schema (generated by `generateSchemaStatements`): what reads it, and what writes it. */
interface SchemaStatements<Q> {
    val reads: List<SchemaStatement<Q>>
    val writes: List<SchemaStatement<Q>>
}

/**
 * A production schema as the clauses address it: its generated database over a driver, that database's queries,
 * and the oldest version a migration still ships from, with one row in it.
 */
private class ProductionSchema<D : Transacter, Q>(
    val label: String,
    val schema: SqlSchema<QueryResult.Value<Unit>>,
    val database: (SqlDriver) -> D,
    val queries: (D) -> Q,
    val statements: SchemaStatements<Q>,
    val firstVersion: Long,
    val firstSchema: List<String>,
)

// ---- the oldest schemas a migration still ships from (shared with the services' migration suites) ----------------

/** `ledger.db` at version 12 — what the squashed migrations up to 11.sqm leave, and the shape 12.sqm meets. */
val LEDGER_V12: List<String> = listOf(
    "CREATE TABLE ledgerRow (key TEXT NOT NULL PRIMARY KEY, assetId TEXT NOT NULL, state TEXT NOT NULL, " +
        "creationDate TEXT NOT NULL DEFAULT '', role TEXT NOT NULL DEFAULT '', contentType TEXT NOT NULL DEFAULT '', " +
        "originalFilename TEXT NOT NULL DEFAULT '', destinationPath TEXT)",
    "CREATE INDEX ledgerRow_assetId ON ledgerRow(assetId)",
    "CREATE INDEX ledgerRow_destinationPath ON ledgerRow(destinationPath)",
    "CREATE TABLE manifestVersion (id INTEGER NOT NULL PRIMARY KEY CHECK (id = 0), value INTEGER NOT NULL)",
    versionTrigger("insert", "INSERT", ""),
    versionTrigger("delete", "DELETE", ""),
    versionTrigger(
        "update",
        "UPDATE",
        " AND (old.key IS NOT new.key OR old.assetId IS NOT new.assetId OR old.creationDate IS NOT new.creationDate " +
            "OR old.role IS NOT new.role OR old.contentType IS NOT new.contentType " +
            "OR old.originalFilename IS NOT new.originalFilename)",
    ),
)

private fun versionTrigger(name: String, event: String, condition: String) =
    "CREATE TRIGGER ledgerRow_version_$name AFTER $event ON ledgerRow BEGIN " +
        "INSERT INTO manifestVersion (id, value) SELECT 0, 0 WHERE NOT EXISTS (SELECT 1 FROM manifestVersion WHERE id = 0); " +
        "UPDATE manifestVersion SET value = value + 1 WHERE id = 0$condition; END"

/** `downloads.db` at version 5 — the shape 5.sqm meets. */
val DOWNLOADS_V5: List<String> = listOf(
    "CREATE TABLE downloadAsset (sourceDeviceId TEXT NOT NULL, sourceAssetId TEXT NOT NULL, state TEXT NOT NULL, " +
        "creationDate TEXT NOT NULL, createdLocalId TEXT, eventId TEXT, PRIMARY KEY (sourceDeviceId, sourceAssetId))",
    "CREATE INDEX downloadAsset_createdLocalId ON downloadAsset(createdLocalId)",
    "CREATE TABLE downloadResource (sourceDeviceId TEXT NOT NULL, sourceAssetId TEXT NOT NULL, resourceKey TEXT NOT NULL, " +
        "url TEXT NOT NULL, role TEXT NOT NULL, contentType TEXT NOT NULL, originalFilename TEXT NOT NULL, stagedPath TEXT, " +
        "enqueued INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (sourceDeviceId, sourceAssetId, resourceKey))",
)

/** `downloads.db` at version 6 — what 5.sqm leaves, the oldest a device holds, and the shape 6.sqm meets. */
val DOWNLOADS_V6: List<String> =
    DOWNLOADS_V5 + "CREATE TABLE unionCursor (eventId TEXT NOT NULL PRIMARY KEY, cursor INTEGER NOT NULL)"

/** The column encoding is the services' business; a statement needs only a value it can bind and read back. */
private object AssetIdText : ColumnAdapter<AssetId, String> {
    override fun decode(databaseValue: String) = AssetId(databaseValue)
    override fun encode(value: AssetId) = value.value
}

private val LEDGER = ProductionSchema(
    label = "ledger",
    schema = LedgerDatabase.Schema,
    database = {
        LedgerDatabase(
            it,
            LedgerRow.Adapter(assetIdAdapter = AssetIdText, stateAdapter = EnumColumnAdapter()),
        )
    },
    queries = { it.ledgerQueries },
    statements = LedgerStatements,
    firstVersion = 12,
    firstSchema = LEDGER_V12 + "INSERT INTO ledgerRow VALUES ('k', 'A', 'COMPLETED', '', '', '', '', NULL)",
)

private val DOWNLOADS = ProductionSchema(
    label = "downloads",
    schema = DownloadDatabase.Schema,
    database = {
        DownloadDatabase(
            it,
            DownloadAsset.Adapter(
                sourceAssetIdAdapter = AssetIdText,
                stateAdapter = EnumColumnAdapter(),
                createdLocalIdAdapter = AssetIdText,
            ),
            DownloadResource.Adapter(sourceAssetIdAdapter = AssetIdText),
        )
    },
    queries = { it.downloadStoreQueries },
    statements = DownloadStoreStatements,
    firstVersion = 5,
    firstSchema = DOWNLOADS_V5 + "INSERT INTO downloadAsset VALUES ('DEV-A', 'OLD', 'IMPORTED', '', 'LOCAL-OLD', 'E1')",
)

/** [production] at its oldest migrated-from version, as a schema the port can create: those tables, holding a row. */
private fun firstVersionOf(production: ProductionSchema<*, *>) = object : SqlSchema<QueryResult.Value<Unit>> {
    override val version = production.firstVersion
    override fun create(driver: SqlDriver) =
        QueryResult.Value(production.firstSchema.forEach { driver.execute(null, it, 0) })

    override fun migrate(driver: SqlDriver, oldVersion: Long, newVersion: Long, vararg callbacks: AfterVersion) =
        QueryResult.Value(Unit)
}

private fun Databases.openedReadWrite(name: String, schema: SqlSchema<QueryResult.Value<Unit>>): SqlDriver {
    val opened = open(name, schema, readOnly = false)
    assertIs<DbOpen.Opened>(opened, "expected $name to open read-write, got $opened")
    return opened.driver
}

/**
 * Runs every statement of [production] on [driver]: each read on the database as it is, then each write in a
 * transaction that is rolled back — the reads run again inside it, so they also see a row the write left. A
 * failure names the statement: what failed is this platform's SQLite, not a service rule.
 */
private fun <D : Transacter, Q> runEveryStatement(production: ProductionSchema<D, Q>, driver: SqlDriver) {
    val database = production.database(driver)
    val queries = production.queries(database)
    fun SchemaStatement<Q>.runHere() = try {
        run(queries)
    } catch (e: Exception) {
        throw AssertionError("${production.label}.$name failed on this SQLite: ${e.message}", e)
    }
    production.statements.reads.forEach { it.runHere() }
    production.statements.writes.forEach { write ->
        database.transaction {
            write.runHere()
            production.statements.reads.forEach { it.runHere() }
            rollback()
        }
    }
}

/**
 * What a schema IS, independent of the order it was built in: its objects, each table's columns, each index's.
 * A column's DEFAULT is left out: `ADD COLUMN … NOT NULL` must carry one that the created table need not, and every
 * write names the column anyway.
 */
private fun SqlDriver.shape(): List<String> {
    val objects = rows("SELECT type, name, tbl_name FROM sqlite_master WHERE name NOT LIKE 'sqlite_%'", 3)
    val columns = objects.filter { it[0] == "table" }.flatMap { (_, table) ->
        rows("SELECT name, type, \"notnull\", pk FROM pragma_table_info('$table')", 4)
            .map { listOf("column", table) + it }
    }
    val indexed = objects.filter { it[0] == "index" }.flatMap { (_, index) ->
        rows("SELECT seqno, name FROM pragma_index_info('$index')", 2).map { listOf("indexed", index) + it }
    }
    return (objects + columns + indexed).map { it.joinToString(" ") }.sorted()
}

private fun SqlDriver.rows(sql: String, width: Int): List<List<String?>> =
    executeQuery(null, sql, { c ->
        QueryResult.Value(buildList { while (c.next().value) add((0 until width).map { c.getString(it) }) })
    }, 0).value

/**
 * The production schemas' clauses (`docs/testing.md`, "Every statement runs on every SQLite"): the services' rules
 * are tested over the mocks on the JVM, so these are what keep each platform's own SQLite executing every
 * statement of `ledger.db` and `downloads.db` — through the port, on a database the adapter created or migrated.
 *
 * They assert that a statement RUNS, never what it answers: that is the services' contract, not the platform's.
 */
internal fun ClauseList<DatabasesState, Databases>.schemaClauses() {
    listOf(LEDGER, DOWNLOADS).forEach { production ->
        val prefix = production.label.uppercase()

        clause(
            "${prefix}_SCHEMA_EVERY_STATEMENT_RUNS",
            DatabasesState.ABSENT,
            covers = cells { on<Databases>().answers(Databases::open).with(DbOpen.Opened::class) },
        ) { databases ->
            val driver = databases.openedReadWrite("${production.label}.db", production.schema)
            runEveryStatement(production, driver)
            driver.close()
        }

        clause(
            "${prefix}_SCHEMA_MIGRATES_FROM_ITS_FIRST_VERSION",
            DatabasesState.ABSENT,
            covers = cells { on<Databases>().answers(Databases::open).with(DbOpen.Opened::class) },
        ) { databases ->
            databases.openedReadWrite("migrated.db", firstVersionOf(production)).close()
            val migrated = databases.openedReadWrite("migrated.db", production.schema)
            val created = databases.openedReadWrite("created.db", production.schema)
            assertEquals(
                created.shape(),
                migrated.shape(),
                "a migrated ${production.label} database is the created one",
            )
            created.close()
            runEveryStatement(production, migrated)
            migrated.close()
        }
    }
}
