/**
 * Derive the landing page's screenshot images from the committed raw captures (`screenshots/`) and emit
 * them as `src/shots.generated.ts` — base64 `data:` URIs the page inlines (capability `marketing-site`:
 * every image is inlined, so the page issues no external network request).
 *
 * BUILD TIME, NEVER RUNTIME. `deno bundle` folds the generated module into the single Edge Script bundle,
 * which is served from memory — `marketing-site` forbids a runtime filesystem read, and
 * `backend-deployment` requires everything to ship in the bundle with the code that reads it.
 *
 * PURE WASM, NO SYSTEM DEPENDENCY. @jsquash is Squoosh's codecs repackaged as WASM, so this runs anywhere
 * Deno does. That is the point: the backend's checks must stay runnable from a fresh clone with only Deno
 * installed — requiring ImageMagick for a Deno backend's unit tests would be a bad trade. (The App Store
 * compositor DOES use ImageMagick, but that is CI-only and needs text rendering.)
 *
 * WebP, not AVIF: measured 15-21 KB per shot at 640px — AVIF would save ~25% for an extra dependency, and
 * the compression win is the codec, not the downscale.
 *
 * The set it emits comes from [SHOTS], the same committed contract `app.ts` reads, and it declares itself
 * [ShotDataUris] — so if this script and the page ever disagree about which captures exist, `deno check`
 * says so rather than the public page doing.
 *
 * Usage: deno task shots        (from backend/)
 */
import { decode as decodePng } from "@jsquash/png";
import resize from "@jsquash/resize";
import { encode as encodeWebp } from "@jsquash/webp";
import { encodeBase64 } from "@std/encoding/base64";
import { rawFilename, type Shot, SHOTS } from "../src/shots.ts";

/**
 * Display width is ~290 CSS px in the carousel; 640 is 2x for retina with room to spare. The raws are
 * 1320x2868, so this is ~23% of the pixels — inlining them full-size would be ~5x the bytes for pixels
 * no one can see.
 */
const TARGET_WIDTH = 640;
const QUALITY = 80;

const RAW_DIR = new URL("../../screenshots/", import.meta.url);
const OUT = new URL("../src/shots.generated.ts", import.meta.url);

async function derive(shot: Shot): Promise<string> {
  const name = rawFilename(shot);
  let raw: Uint8Array;
  try {
    raw = await Deno.readFile(new URL(name, RAW_DIR));
  } catch {
    throw new Error(
      `missing raw capture ${name} — dispatch .github/workflows/screenshots.yml, download the ` +
        `artifact, and commit the 6 raws to screenshots/ (see CLAUDE.md)`,
    );
  }
  const img = await decodePng(raw);
  const small = await resize(img, {
    width: TARGET_WIDTH,
    height: Math.round((img.height * TARGET_WIDTH) / img.width),
  });
  const webp = await encodeWebp(small, { quality: QUALITY });
  return `data:image/webp;base64,${encodeBase64(new Uint8Array(webp))}`;
}

const entries: string[] = [];
let total = 0;
for (const shot of SHOTS) {
  const uri = await derive(shot);
  total += uri.length;
  entries.push(`  ${shot.placeholder}:\n    "${uri}",`);
  console.log(`  ${rawFilename(shot)}: ${(uri.length / 1024).toFixed(1)} KB (base64)`);
}

// Typed as ShotDataUris, so a capture this script failed to emit — or a key it spelled differently from the
// contract — is a compile error here rather than a `{{SHOT_…}}` on the public page.
const src =
  `// GENERATED by \`deno task shots\` from the committed raws in screenshots/ — DO NOT EDIT.
// Not committed: it is derived, and regenerating is a task away. See scripts/shots.ts.

import type { ShotDataUris } from "./shots.ts";

export const SHOT_DATA_URIS: ShotDataUris = {
${entries.join("\n")}
};
`;
await Deno.writeTextFile(OUT, src);
console.log(
  `wrote ${OUT.pathname} — ${
    (total / 1024).toFixed(1)
  } KB of base64 across ${entries.length} images`,
);
