plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
}

// The event link's origin, generated from the `snapsync.domain` property (gradle.properties) so the
// app has exactly one source for it. Config.xcconfig reads the same property's value for the
// `applinks:` entitlement; the backend's copy is unreachable from here and is held by a
// :test:architecture guard instead (capability `event-link`).
val linkDomain: String = providers.gradleProperty("snapsync.domain").get()

val generateLinkOrigin by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/linkOrigin/kotlin")
    val domain = linkDomain
    inputs.property("domain", domain)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().asFile.resolve("app/snapsync/config/LinkOrigin.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            // GENERATED by :capability:config's generateLinkOrigin task — do not edit.
            // Source of truth: the `snapsync.domain` property in gradle.properties.
            package app.snapsync.config

            /**
             * The event link's canonical origin (capability `event-link`). Both halves of the codec are
             * anchored here: [encodeEventUrl] emits it and [decodeEventUrl] matches it, so producer and
             * consumer cannot drift.
             */
            public const val LINK_ORIGIN: String = "https://$domain"

            """.trimIndent(),
        )
    }
}

kotlin {
    jvmToolchain(libs.versions.jdk.get().toInt())
    jvm()
    iosArm64()
    iosSimulatorArm64()
    sourceSets {
        commonMain.configure { kotlin.srcDir(generateLinkOrigin) }
        commonMain.dependencies {
            api(libs.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            // Capability `photo-selection-policy`: "now" + local→UTC conversion for the capture-date cutoff.
            implementation(libs.kotlinx.datetime)
            // The three-state Keychain read (`KeychainRead`) that `ConfigRead` is derived from —
            // `api`, because it appears in `configReadFrom`'s public signature. The mapping is pure and
            // lives in commonMain so "unreadable is not absent" is tested on JVM and the simulator.
            api(project(":domain:keychain"))
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.coroutines.test)
        }
        iosMain.dependencies {
            // The Keychain store logs a legacy-item decode failure (capability `photo-selection-policy`):
            // a cutoff-less item reads as no config, and that must be diagnosable, not mysterious.
            implementation(libs.kermit)
        }
    }
}
