import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeSimulatorTest

// The `:domain` core (spec `module-architecture`): one module, ZERO project() dependencies, no
// `iosMain` source directory (the targets exist so iosMain elsewhere can compile against it; the
// module itself is platform-free). Zones live as packages under src/*/kotlin — `model/` and
// `ports/` born in migration step 3a; `feature/`, `flow/`, `compose/` follow in later steps. The
// zone import laws are enforced by the self-arming gates in `:test:architecture`
// (capability `architecture-guards`).

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
}

// Full failure messages in CI: the Kotlin/Native simulator runner otherwise prints a terse
// "AssertionError at null:-1" with no expected/actual, which is useless for diagnosing
// platform-specific test failures.
tasks.withType<KotlinNativeSimulatorTest>().configureEach {
    testLogging {
        exceptionFormat = TestExceptionFormat.FULL
        showStandardStreams = true
    }
}

// The event link's origin, generated from the `snapsync.domain` property (gradle.properties) so the
// app has exactly one source for it — moved here with the `EventLink` codec (migration step 3a);
// `:capability:config`'s copy of this task must be deleted when that module stops compiling the
// codec, or two modules generate the same const. Config.xcconfig reads the same property's value
// for the `applinks:` entitlement; the backend's copy is unreachable from here and is held by a
// :test:architecture guard instead (capability `event-link`).
val linkDomain: String = providers.gradleProperty("snapsync.domain").get()

val generateLinkOrigin by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/linkOrigin/kotlin")
    val domain = linkDomain
    inputs.property("domain", domain)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().asFile.resolve("app/snapsync/model/LinkOrigin.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            // GENERATED by :domain's generateLinkOrigin task — do not edit.
            // Source of truth: the `snapsync.domain` property in gradle.properties.
            package app.snapsync.model

            /**
             * The event link's canonical origin (capability `event-link`). Both halves of the codec are
             * anchored here: [encodeEventUrl] emits it and [decodeEventUrl] matches it, so producer and
             * consumer cannot drift.
             */
            public const val LINK_ORIGIN: String = "https://$domain"

            """.trimIndent(),
        )
    }
}

kotlin {
    jvmToolchain(libs.versions.jdk.get().toInt())
    jvm()
    iosArm64()
    iosSimulatorArm64()
    sourceSets {
        commonMain.configure { kotlin.srcDir(generateLinkOrigin) }
        commonMain.dependencies {
            // The per-zone library allowlist (spec `module-architecture`, "Core purity is closed by
            // default"): coroutines (StateFlow/Flow port shapes), serialization + datetime (the
            // config/manifest vocabulary and cutoff codecs), kermit (the engine's diagnostics).
            api(libs.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kermit)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.coroutines.test)
        }
        // NO iosMain block, ever: `:domain` has no iosMain source directory (spec
        // `module-architecture`; guard: the zone gates' D6 scope + `compileIosMainKotlinMetadata`).
    }
}
