import org.gradle.api.tasks.testing.logging.TestExceptionFormat
import org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeSimulatorTest

// The `:domain` core (spec `module-architecture`): one module, ZERO project() dependencies, no
// `iosMain` source directory (the targets exist so iosMain elsewhere can compile against it; the
// module itself is platform-free). Zones live as packages under src/*/kotlin — `model/` and
// `ports/` born in migration step 3a; `feature/`, `flow/`, `compose/` follow in later steps. The
// zone import laws are enforced by the self-arming gates in `:test:architecture`
// (capability `architecture-guards`).

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.kotlin.serialization)
}

// Full failure messages in CI: the Kotlin/Native simulator runner otherwise prints a terse
// "AssertionError at null:-1" with no expected/actual, which is useless for diagnosing
// platform-specific test failures.
tasks.withType<KotlinNativeSimulatorTest>().configureEach {
    testLogging {
        exceptionFormat = TestExceptionFormat.FULL
        showStandardStreams = true
    }
}

// The event link's origin, generated from the RESOLVED DEPLOYMENT (capability
// `deployment-configuration`) so the app, the backend, the xcconfig and the site all derive it from one
// declared value rather than each holding a copy. `snapsync.deployment` names WHICH deployment; the
// resolver renders it to `build/deployment.properties`, which Gradle reads natively.
//
// The resolver is invoked here at CONFIGURATION time because `LINK_ORIGIN` is generated into a source
// set. It is stdlib-only Python — the one runtime present on every runner and dev machine that also has
// Gradle (no CI job carries both Deno and Gradle, so the backend's runtime could not be the resolver).
val deploymentName: String = providers.gradleProperty("snapsync.deployment").get()

val resolvedDeployment: Map<String, String> = run {
    val repoRoot = rootProject.layout.projectDirectory.asFile
    providers.exec {
        workingDir(repoRoot)
        commandLine("python3", "scripts/resolve-deployment.py", deploymentName, "--quiet")
    }.result.get().assertNormalExitValue()
    val rendered = repoRoot.resolve("build/deployment.properties")
    check(rendered.isFile) { "the resolver produced no ${rendered.path} — cannot generate LINK_ORIGIN" }
    rendered.readLines()
        .filterNot { it.isBlank() || it.startsWith("#") }
        .associate { line -> line.substringBefore('=') to line.substringAfter('=') }
}

val linkDomain: String = requireNotNull(resolvedDeployment["domain"]) {
    "deployment '$deploymentName' resolved no `domain` — the event link has no origin"
}

val generateLinkOrigin by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/linkOrigin/kotlin")
    val domain = linkDomain
    inputs.property("domain", domain)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().asFile.resolve("app/snapsync/model/LinkOrigin.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            // GENERATED by :domain's generateLinkOrigin task — do not edit.
            // Source of truth: the resolved deployment (see deployments/ and scripts/resolve-deployment.py).
            package app.snapsync.model

            /**
             * The event link's canonical origin (capability `event-link`). Both halves of the codec are
             * anchored here: [encodeEventUrl] emits it and [decodeEventUrl] matches it, so producer and
             * consumer cannot drift.
             */
            public const val LINK_ORIGIN: String = "https://$domain"

            """.trimIndent(),
        )
    }
}

kotlin {
    jvmToolchain(libs.versions.jdk.get().toInt())
    jvm()
    iosArm64()
    iosSimulatorArm64()
    sourceSets {
        commonMain.configure { kotlin.srcDir(generateLinkOrigin) }
        commonMain.dependencies {
            // The per-zone library allowlist (spec `module-architecture`, "Core purity is closed by
            // default"): coroutines (StateFlow/Flow port shapes), serialization + datetime (the
            // config/manifest vocabulary and cutoff codecs), kermit (the engine's diagnostics).
            api(libs.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kermit)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.coroutines.test)
        }
        // NO iosMain block, ever: `:domain` has no iosMain source directory (spec
        // `module-architecture`; guard: the zone gates' D6 scope + `compileIosMainKotlinMetadata`).
    }
}
