// `:adapter:ios:ext-safe` (`docs/architecture.md`): every iOS adapter the background-upload
// EXTENSION process links — placed by linkage, so the extension binary's contents are decided by
// this module boundary rather than by luck. The extension-safety text gate
// (`:test:architecture` ExtensionSafetyTest) forbids `platform.UIKit`/`platform.BackgroundTasks`
// anywhere under this module, because Kotlin/Native does not model `NS_EXTENSION_UNAVAILABLE`.
// This is also the Keychain containment module — the ONLY module that may touch `SecItem*`
// (`docs/architecture.md`; KeychainContainmentTest).

plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

// ---- Port contracts (`docs/architecture.md`) ---------------------------------------------------
//
// `src/rig/kotlin` holds the Keychain's recording/replaying seams and the entitled-device binding. Under
// `-Psnapsync.rig=true` it compiles into `iosMain` — the device app records through it — together with
// `:test:contracts`, and a build without the property contains neither (`docs/architecture.md`, "A
// build-time-only module is contained by compilation"). Otherwise it compiles into `iosTest`, where CI
// replays through it — so the recorder and the replayer are one file, and the device path is compile-checked
// on every build.
val rigEnabled = providers.gradleProperty("snapsync.rig").map(String::toBoolean).getOrElse(false)

// The committed recordings, embedded into the replay tests as Kotlin constants. Embedded rather than read at
// run time so the simulator test executable needs no path into the repository; the `.rec` files stay the
// single source, and nothing is copied by hand.
val contractRecordings = rootProject.layout.projectDirectory.dir("test/contracts/recordings")
val generatedRecordings = layout.buildDirectory.dir("generated/contractRecordings/kotlin")
val embedContractRecordings = tasks.register("embedContractRecordings") {
    val sources = fileTree(contractRecordings) { include("*.rec") }
    val out = generatedRecordings
    inputs.files(sources)
    outputs.dir(out)
    doLast {
        val entries = sources.files.sortedBy { it.name }.joinToString("") { f ->
            val text = f.readText()
            check("\"\"\"" !in text) { "${f.name} contains a triple quote and cannot be embedded" }
            "    \"${f.nameWithoutExtension}\" to \"\"\"" + text.replace("$", "\${'$'}") + "\"\"\",\n"
        }
        val file = out.get().file("app/snapsync/keychain/contract/Recordings.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            "package app.snapsync.keychain.contract\n\n" +
                "// GENERATED by :adapter:ios:ext-safe:embedContractRecordings from test/contracts/recordings/*.rec\n" +
                "internal val RECORDINGS: Map<String, String> = mapOf(\n" + entries + ")\n",
        )
    }
}

kotlin {
    iosArm64()
    iosSimulatorArm64()

    iosSimulatorArm64().binaries.all {
        if (this is org.jetbrains.kotlin.gradle.plugin.mpp.TestExecutable) {
            // `-lsqlite3`: the sqliter cinterop that backs `NativeSqliteDriver` declares this
            // itself, but only for a compilation that depends on the driver DIRECTLY — here it is
            // an `implementation` dep of commonMain, and the option does not reach the test
            // executable's own link. It goes unnoticed until a test actually opens a database
            // (`IosLedgerStoreTest`, `IosDownloadStoreTest`), at which point the link fails with a
            // wall of undefined `_sqlite3_*` symbols. The system library is present on every Apple
            // platform; this only tells the linker to use it.
            linkerOpts("-lsqlite3")
        }
    }
    sourceSets {
        if (rigEnabled) {
            iosMain { kotlin.srcDir("src/rig/kotlin") }
        } else {
            iosTest { kotlin.srcDir("src/rig/kotlin") }
        }
        iosMain.dependencies {
            if (rigEnabled) {
                implementation(project(":test:contracts"))
                implementation(project(":domain:services"))
            }
        }
        iosTest { kotlin.srcDir(embedContractRecordings) }
        commonMain.dependencies {
            api(project(":domain:model"))
            api(project(":domain:ports"))
            api(project(":domain:feature"))
            // The Ktor core types darwinHttpClient() returns.
            api(project(":adapter:generic:app"))
            // (The interim :capability:album and :domain:gallery edges died at migration step 6:
            // the album seams now live in :domain ports/, albumMapSource in feature/album, and the
            // ResourceEnumerator composition in feature/upload — all reached via api(":domain").)
            implementation(libs.sqldelight.driver.native)
            implementation(libs.ktor.client.darwin)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kermit)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            // The Keychain and App-Group store bindings of `SecureStoreContract` (capability
            // `docs/architecture.md`). Bound here because the seam and `AppGroupFileSecureStore` are `internal`.
            implementation(project(":test:contracts"))
            // The photo-library contracts bind the grant-aware composition production calls over the
            // PhotoKit adapters (`docs/architecture.md`, "A live binding binds the composition
            // production calls").
            implementation(project(":domain:compose"))
            // The storage services' SQLite behaviour on this target, measured over the real `IosDatabases`
            // (`docs/architecture.md`): a `:domain:*` build file names no module, so those tests live here.
            implementation(project(":domain:services"))
        }
    }
}
