// `:adapter:ios:app-only` (spec `module-architecture`): iOS adapters only the MAIN APP process
// links — placed by linkage. Two reference app-only OS surfaces outright (`BGTaskScheduler`);
// the others are app-process-bound by identity or need: `IosUrlSessionUploadPlatform` and
// `IosDownloadTransport` own background-`URLSession` ids the OS reattaches to the app process
// across relaunch (a second, extension-side claimant of an OS-held session identity must be
// structurally impossible), `IosPhotoLibraryImporter` is the download feature's import writer,
// and `PhotoLibraryPermission` requests authorization where the system sheet can present.
// Keeping them out of `:adapter:ios:ext-safe` keeps the extension binary lean and the
// extension-safety gate scoped to code the appex can actually contain.

plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

// ---- Port contracts (capability `port-contracts`) ---------------------------------------------------
//
// `src/rig/kotlin` holds the simulator app's live bindings of the photo-library contracts: every PhotoKit adapter
// of both iOS adapter modules, run under the full grant only an app bundle can hold. They live here rather than
// beside each adapter because a rig directory compiles into its module's `iosTest` without the property, and one
// module's tests cannot see another's; this module sees both modules' adapters. Under `-Psnapsync.rig=true` the
// directory compiles into `iosMain`, together with `:test:contracts`, and a build without the property contains
// neither (`module-architecture`, "A build-time-only module is contained by compilation"). Otherwise it compiles
// into `iosTest`, so the bindings are compile-checked on every build.
val rigEnabled = providers.gradleProperty("snapsync.rig").map(String::toBoolean).getOrElse(false)

// The committed recordings, embedded into this module's replay tests as Kotlin constants — the twin of
// `:adapter:ios:ext-safe`'s task of the same name, which embeds them for the Keychain's replay. Each module
// needs its own: the generated map is `internal` to the test compilation it lands in.
val contractRecordings = rootProject.layout.projectDirectory.dir("test/contracts/recordings")
val generatedRecordings = layout.buildDirectory.dir("generated/contractRecordings/kotlin")
val embedContractRecordings by tasks.registering {
    val sources = fileTree(contractRecordings) { include("*.rec") }
    val out = generatedRecordings
    inputs.files(sources)
    outputs.dir(out)
    doLast {
        val entries = sources.files.sortedBy { it.name }.joinToString("") { f ->
            val text = f.readText()
            check("\"\"\"" !in text) { "${f.name} contains a triple quote and cannot be embedded" }
            "    \"${f.nameWithoutExtension}\" to \"\"\"" + text.replace("$", "\${'$'}") + "\"\"\",\n"
        }
        val file = out.get().file("app/snapsync/contract/Recordings.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            "package app.snapsync.contract\n\n" +
                "// GENERATED by :adapter:ios:app-only:embedContractRecordings from test/contracts/recordings/*.rec\n" +
                "internal val RECORDINGS: Map<String, String> = mapOf(\n" + entries + ")\n",
        )
    }
}

kotlin {
    iosArm64()
    iosSimulatorArm64()

    // Sentry test-link (capability `crash-reporting`): this module's simulator TEST binary links
    // :adapter:ios:ext-safe (api) and therefore Sentry symbols — even with no test sources, K/N
    // still links an empty test.kexe. Reuse the Sentry-Dynamic framework ext-safe provisions.
    val sentrySimulatorSlice = project(":adapter:ios:ext-safe").layout.buildDirectory
        .dir("sentry-cocoa/${libs.versions.sentry.cocoa.get()}/Sentry-Dynamic.xcframework/ios-arm64_x86_64-simulator")
        .get().asFile.toString()
    iosSimulatorArm64().binaries.all {
        if (this is org.jetbrains.kotlin.gradle.plugin.mpp.TestExecutable) {
            linkTaskProvider.configure { dependsOn(":adapter:ios:ext-safe:provisionSentryCocoa") }
            linkerOpts("-F$sentrySimulatorSlice", "-rpath", sentrySimulatorSlice)
        }
    }
    sourceSets {
        if (rigEnabled) {
            iosMain { kotlin.srcDir("src/rig/kotlin") }
        } else {
            iosTest { kotlin.srcDir("src/rig/kotlin") }
        }
        iosTest { kotlin.srcDir(embedContractRecordings) }
        iosMain.dependencies {
            if (rigEnabled) {
                implementation(project(":test:contracts"))
                implementation(project(":domain:compose"))
            }
        }
        commonMain.dependencies {
            api(project(":domain:model"))
            api(project(":domain:ports"))
            // The shared PhotoKit discovery walk (IosDiscovery) the URLSession tier reuses.
            api(project(":adapter:ios:ext-safe"))
            implementation(libs.coroutines.core)
            implementation(libs.kermit)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            // The contract bindings of this module's adapters (capability `port-contracts`): the live
            // `StagedBytesContract` binding beside `IosStagedBytes`, and the photo-library contracts over
            // the grant-aware composition production calls.
            implementation(project(":test:contracts"))
            implementation(project(":domain:compose"))
        }
    }
}

// Full failure messages in CI (same configuration as `:adapter:generic:app`): the Kotlin/Native
// simulator runner otherwise prints a terse "AssertionError at null:-1" with no message and no
// line, which makes a red iOS-only test unreadable from Linux — the one place these tests cannot
// be re-run.
tasks.withType<org.jetbrains.kotlin.gradle.targets.native.tasks.KotlinNativeSimulatorTest>().configureEach {
    testLogging {
        exceptionFormat = org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
        // Standard streams stay OFF, unlike `:adapter:generic:app`: `DarwinHttpClientTest` aims
        // requests at a closed port on purpose, and the client's own failure logging would then
        // print a multi-line NSError with a stack trace for each one — burying real output.
    }
}
