#!/usr/bin/env -S uv run --quiet --with cryptography python
# Regenerates test/vectors/encrypted-file.json — the reference vectors both halves of the encrypted file
# format are held to (`api/src/encrypted-file.ts`, `:domain:model`'s EncryptedFileFormat). Deliberately an
# implementation INDEPENDENT of both, over pyca/cryptography; the JVM test additionally decrypts every vector
# with Google Tink, so the format is Tink's by measurement, not by reading. Deterministic: re-running it
# rewrites the same file.
import json, struct, hashlib
from pathlib import Path
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.hkdf import HKDF
from cryptography.hazmat.primitives import hashes

def hkdf(ikm, salt, info, n):
    return HKDF(algorithm=hashes.SHA256(), length=n, salt=salt, info=info).derive(ikm)

def tink_stream(ikm, ad, salt, prefix, pt, seg):
    key = hkdf(ikm, salt, ad, 32)
    header = bytes([1 + len(salt) + len(prefix)]) + salt + prefix
    out, pos, i = bytearray(header), 0, 0
    first = seg - len(header) - 16
    while True:
        size = first if i == 0 else seg - 16
        chunk = pt[pos:pos + size]; pos += len(chunk)
        last = pos >= len(pt)
        nonce = prefix + struct.pack(">I", i) + bytes([1 if last else 0])
        out += AESGCM(key).encrypt(nonce, chunk, None); i += 1
        if last: return bytes(out)

def ct_fields(ct):
    if len(ct) <= 2048: return {"ciphertext": ct.hex()}
    return {"ciphertextLength": len(ct), "ciphertextHead": ct[:64].hex(), "ciphertextSha256": hashlib.sha256(ct).hexdigest()}

def key_id(event_key):
    return hkdf(event_key, b"", b"snapsync/key-id/v1", 8)

def ad(e, d, a, r):
    return f"snapsync/v1/{e}/{d}/{a}/{r}".encode()

event_key = bytes(range(32))
salt = bytes(range(0x40, 0x60)); prefix = bytes(range(0xa0, 0xa7))
ids = ("0a1b2c3d-0000-4000-8000-000000000001", "0a1b2c3d-0000-4000-8000-000000000002", "AB12CD34-5678_L0_001", "primary")
vectors = {"about": "SnapSync encrypted-file reference vectors. Plaintext byte i of a stream vector = (i*7+3) & 0xff, of the file vector = (i*13+1) & 0xff. Generated by an implementation independent of the app (Python cryptography) and decrypted by Google Tink 1.23.0 AesGcmHkdfStreaming(HmacSha256, 32, segmentSize, 0). Ciphertexts over 2 KiB are pinned by length, first 64 bytes and SHA-256.", "keyId": [], "stream": [], "file": []}
for k in [event_key, bytes(32), bytes([0xff]) * 32]:
    vectors["keyId"].append({"eventKey": k.hex(), "keyId": key_id(k).hex()})
for seg in [64, 65536]:
    first = seg - 40 - 16; rest = seg - 16
    for n in sorted({0, 1, first - 1, first, first + 1, first + rest, first + rest + 1, first + 2 * rest + 5}):
        pt = bytes((i * 7 + 3) & 0xff for i in range(n))
        a = ad(*ids)
        vectors["stream"].append({"segmentSize": seg, "ikm": event_key.hex(), "associatedData": a.hex(),
            "salt": salt.hex(), "noncePrefix": prefix.hex(), "plaintextLength": n,
            **ct_fields(tink_stream(event_key, a, salt, prefix, pt, seg))})
pt = bytes((i * 13 + 1) & 0xff for i in range(200_000))
body = tink_stream(event_key, ad(*ids), salt, prefix, pt, 65536)
vectors["file"].append({"eventKey": event_key.hex(), "eventId": ids[0], "deviceId": ids[1], "assetId": ids[2], "role": ids[3],
    "salt": salt.hex(), "noncePrefix": prefix.hex(), "plaintextLength": len(pt), **{("file" + k[10:]): v for k, v in ct_fields(bytes([1]) + key_id(event_key) + body).items()}})
json.dump(vectors, open(Path(__file__).resolve().parent.parent / "test/vectors/encrypted-file.json", "w"), indent=1)
print(len(vectors["stream"]), "stream vectors")
