package app.snapsync.tools.diagrams

/**
 * The DI wiring / binary × port matrix, current-state edition: which composition root constructs
 * which repo-declared type. THE POINT: a row where one root differs from its siblings without a
 * documented reason is the per-tier-drift instrument — the class of defect behind the app-driven
 * tier shipping without a re-join reconciler, and behind the harness mirror that was more correct
 * than production — rendered visible in the PR diff that introduces it, BEFORE the migration's
 * shared `compose/` functions make such drift structurally impossible.
 *
 * Scope is DERIVED: a root is any top-level `class`/`object` under `app/` or `test/world/`
 * whose leading KDoc's first paragraph calls it a composition root. A constructed type counts only
 * when it is a `class`/`object` declared in this repository (platform and stdlib constructors are
 * wiring noise, not ports).
 */
fun diMarkdown(sources: List<KtSource>): String {
    // Every class/object declared anywhere in the scanned tree — the "repo-declared" filter.
    val repoClasses = sources
        .flatMap { declarations(it) }
        .filter { it.kind != "interface" }
        .map { it.name }
        .toSet()

    data class Root(val name: String, val source: KtSource)

    val roots = sources
        .filter { it.relPath.startsWith("app/") || it.relPath.startsWith("test/world/") }
        .mapNotNull { source -> rootDeclarationIn(source)?.let { Root(it, source) } }
        .sortedWith(compareBy { it.name })

    val ctor = Regex("(?<![\\w.@])([A-Z][A-Za-z0-9_]*)\\s*\\(")
    val constructedBy = roots.associate { root ->
        val own = declarations(root.source).map { it.name }.toSet()
        root.name to ctor.findAll(root.source.stripped)
            .map { it.groupValues[1] }
            .filter { it in repoClasses && it !in own }
            .toSortedSet(compareBy<String> { it })
    }
    val allConstructed = constructedBy.values.flatten().toSortedSet(compareBy { it })

    val sb = StringBuilder()
    sb.append("# DI wiring — binary × port matrix, current-state edition\n")
    sb.append("\n")
    sb.append("Generated by `./gradlew architectureDiagrams` from a source scan of the composition\n")
    sb.append("roots (derived scope: a top-level `class`/`object` under `app/` or `test/world/` whose\n")
    sb.append("leading KDoc's first paragraph names it a composition root). A cell marks a root that\n")
    sb.append("constructs the type. Do not edit — the `:tools:diagrams` freshness test fails on drift.\n")
    sb.append("\n")
    sb.append("THE POINT of this table: a row where one root differs from its siblings without a\n")
    sb.append("documented reason is the per-tier-drift instrument — the class of defect behind the\n")
    sb.append("per-tier reconciler regression and the harness-mirror drift — working BEFORE the\n")
    sb.append("migration's shared `compose/` functions exist.\n")
    sb.append("\n")
    sb.append("Roots found:\n")
    sb.append("\n")
    for (root in roots) sb.append("- `").append(root.name).append("` — `").append(root.source.relPath).append("`\n")
    sb.append("\n")
    sb.append("| Constructed type |")
    for (root in roots) sb.append(" ").append(root.name).append(" |")
    sb.append("\n")
    sb.append("|---|")
    for (root in roots) sb.append("---|")
    sb.append("\n")
    for (type in allConstructed) {
        sb.append("| `").append(type).append("` |")
        for (root in roots) {
            sb.append(if (type in constructedBy.getValue(root.name)) " x |" else " |")
        }
        sb.append("\n")
    }
    return sb.toString()
}

/**
 * The name of the top-level `class`/`object` this file declares as a composition root, or null.
 * "First paragraph" is the KDoc up to its first blank line — a later paragraph merely *mentioning*
 * a composition root (adapters do) must not enroll the file.
 */
private fun rootDeclarationIn(source: KtSource): String? {
    // The KDoc group is tempered — `(?:(?!\*/).)` — so it can never span ACROSS a `*/` into a later
    // comment: without that, backtracking lets one match swallow several comments and attribute an
    // earlier property's "composition root" mention to an unrelated declaration below.
    val kdocDecl = Regex(
        "/\\*\\*((?:(?!\\*/).)*?)\\*/\\s*((?:@\\w+(?:\\([^)]*\\))?\\s*)*(?:\\w+\\s+)*?)(class|object)\\s+([A-Z][A-Za-z0-9_]*)",
        RegexOption.DOT_MATCHES_ALL,
    )
    for (m in kdocDecl.findAll(source.text)) {
        // Top-level only: the declaration's line starts at column 0 (nested types are indented).
        val declStart = m.groups[3]!!.range.first
        val lineStart = source.text.lastIndexOf('\n', declStart) + 1
        val prefix = source.text.substring(lineStart, declStart)
        if (prefix.firstOrNull()?.isWhitespace() == true) continue
        val firstParagraph = m.groupValues[1]
            .split("\n")
            .map { it.trim().trimStart('*').trim() }
            .dropWhile { it.isEmpty() }
            .takeWhile { it.isNotEmpty() }
            .joinToString(" ")
        if (firstParagraph.contains("composition root", ignoreCase = true)) {
            return m.groupValues[4]
        }
    }
    return null
}
