package app.snapsync.tools.diagrams

import java.io.File

/**
 * Feature cards: one card per `feature/<name>` package in `:domain` (a directory walk — the scope
 * is derived, so a new feature package gets a card with zero edits here), each carrying the
 * feature's files and the top-level types it declares.
 */
fun featuresMarkdown(root: File, sources: List<KtSource>): String {
    val featureRoot = "domain/feature/src/commonMain/kotlin/app/snapsync/feature"

    data class Card(val name: String, val files: List<String>, val types: List<String>)

    val cards = File(root, featureRoot)
        .listFiles { f: File -> f.isDirectory }
        .orEmpty()
        .sortedWith(compareBy { it.name })
        .map { dir ->
            val featureSources = sources.filter { it.relPath.startsWith("$featureRoot/${dir.name}/") }
            Card(
                name = dir.name,
                files = featureSources.map { it.relPath.substringAfterLast('/') }.sortedWith(compareBy { it }),
                types = featureSources
                    .flatMap { declarations(it) }
                    .filter { it.topLevel }
                    .map { "${it.name} (${it.kind})" }
                    .distinct()
                    .sortedWith(compareBy { it }),
            )
        }
    check(cards.isNotEmpty()) {
        "feature-card scan found no feature packages under $featureRoot — the zone moved; " +
            "a diagram that scans nothing must fail, not render empty"
    }

    val sb = StringBuilder()
    sb.append("# Feature cards\n")
    sb.append("\n")
    sb.append("Generated by `./gradlew architectureDiagrams` from a directory walk over `:domain`'s\n")
    sb.append("`feature/` packages. Features are mutually blind (`docs/architecture.md`; the\n")
    sb.append("feature-blindness gate enforces it), so no card lists another feature. Do not edit —\n")
    sb.append("the `:tools:diagrams` freshness test fails on drift; regenerate instead.\n")
    sb.append("\n")
    for (card in cards) {
        sb.append("## `feature/").append(card.name).append("`\n")
        sb.append("\n")
        sb.append("- files: ")
        sb.append(card.files.joinToString(", ") { "`$it`" }.ifEmpty { "—" })
        sb.append("\n")
        sb.append("- top-level types: ")
        sb.append(card.types.joinToString(", ") { "`$it`" }.ifEmpty { "—" })
        sb.append("\n")
        sb.append("\n")
    }
    return sb.toString()
}
