package app.snapsync.tools.diagrams

import java.io.File

/**
 * Feature cards: one card per `feature/<name>` package in `:domain` (a directory walk — the scope
 * is derived, so a new feature package gets a card with zero edits here), each carrying the
 * feature's files and the top-level types it declares. Plus the forge name→sources map (spec
 * requirement): the recognized `SNAPSYNC_FORGE_STATE` presets and the inputs each forges, parsed
 * from the enum in the file that declares `forgeStatusHost` — derived, so adding a marketing state
 * updates the card automatically.
 */
fun featuresMarkdown(root: File, sources: List<KtSource>): String {
    val featureRoot = "domain/feature/src/commonMain/kotlin/app/snapsync/feature"

    data class Card(val name: String, val files: List<String>, val types: List<String>)

    val cards = File(root, featureRoot)
        .listFiles { f: File -> f.isDirectory }
        .orEmpty()
        .sortedWith(compareBy { it.name })
        .map { dir ->
            val featureSources = sources.filter { it.relPath.startsWith("$featureRoot/${dir.name}/") }
            Card(
                name = dir.name,
                files = featureSources.map { it.relPath.substringAfterLast('/') }.sortedWith(compareBy { it }),
                types = featureSources
                    .flatMap { declarations(it) }
                    .filter { it.topLevel }
                    .map { "${it.name} (${it.kind})" }
                    .distinct()
                    .sortedWith(compareBy { it }),
            )
        }
    check(cards.isNotEmpty()) {
        "feature-card scan found no feature packages under $featureRoot — the zone moved; " +
            "a diagram that scans nothing must fail, not render empty"
    }

    val sb = StringBuilder()
    sb.append("# Feature cards\n")
    sb.append("\n")
    sb.append("Generated by `./gradlew architectureDiagrams` from a directory walk over `:domain`'s\n")
    sb.append("`feature/` packages plus a parse of the forge factory's preset enum. Features are\n")
    sb.append("mutually blind (spec `module-architecture`; the feature-blindness gate enforces it), so\n")
    sb.append("no card lists another feature. Do not edit — the `:tools:diagrams` freshness test fails\n")
    sb.append("on drift; regenerate instead.\n")
    sb.append("\n")
    for (card in cards) {
        sb.append("## `feature/").append(card.name).append("`\n")
        sb.append("\n")
        sb.append("- files: ")
        sb.append(card.files.joinToString(", ") { "`$it`" }.ifEmpty { "—" })
        sb.append("\n")
        sb.append("- top-level types: ")
        sb.append(card.types.joinToString(", ") { "`$it`" }.ifEmpty { "—" })
        sb.append("\n")
        sb.append("\n")
    }
    sb.append(forgeMapSection(sources))
    return sb.toString()
}

/**
 * The forge name→sources map (`SNAPSYNC_FORGE_STATE`): each preset of the first enum declared in
 * the file that declares `forgeStatusHost`, with the verbatim forged-input arguments.
 */
private fun forgeMapSection(sources: List<KtSource>): String {
    val sb = StringBuilder()
    sb.append("## Forge name→sources map (`SNAPSYNC_FORGE_STATE`)\n")
    sb.append("\n")
    val forgeFile = sources.firstOrNull { Regex("\\bfun\\s+forgeStatusHost\\s*\\(").containsMatchIn(it.stripped) }
    if (forgeFile == null) {
        sb.append("- no `forgeStatusHost` factory found\n")
        return sb.toString()
    }
    sb.append("Declared in `").append(forgeFile.relPath).append("`.\n")
    sb.append("\n")
    sb.append("| State | Forged inputs |\n")
    sb.append("|---|---|\n")
    val text = forgeFile.stripped
    val enumStart = Regex("\\benum\\s+class\\s+\\w+").find(text)
    if (enumStart != null) {
        val bodyOpen = text.indexOf('{', enumStart.range.last)
        val bodyEnd = skipBalanced(text, bodyOpen, '{', '}') - 1
        // Entries end at the `;` (or the body brace) that separates them from the companion.
        val entriesEnd = text.indexOf(';', bodyOpen).let { if (it in (bodyOpen + 1) until bodyEnd) it else bodyEnd }
        val entry = Regex("(?m)^\\s{4}([A-Z][A-Z_0-9]*)\\s*\\(")
        for (m in entry.findAll(text.substring(bodyOpen, entriesEnd))) {
            val argsOpen = bodyOpen + m.range.last
            val argsEnd = skipBalanced(text, argsOpen, '(', ')') - 1
            val args = text.substring(argsOpen + 1, argsEnd).replace(Regex("\\s+"), " ").trim()
            val state = args.substringBefore(',').trim().trim('"')
            val rest = args.substringAfter(',').trim()
            sb.append("| `").append(state).append("` | `").append(rest).append("` |\n")
        }
    }
    return sb.toString()
}
