package app.snapsync.tools.diagrams

import java.io.File

/**
 * Feature cards, current-state edition: the closest thing to features today are the modules under
 * `domain/` and `capability/`, so one card per module (a directory walk — the scope reshapes
 * itself when the target `feature/` packages land), each carrying the module's declared deps and
 * the interfaces its `commonMain` defines. Plus the forge name→sources map (spec requirement):
 * the recognized `SNAPSYNC_FORGE_STATE` presets and the inputs each forges, parsed from the enum
 * in the file that declares `forgeStatusHost` — derived, so adding a marketing state updates the
 * card automatically.
 */
fun featuresMarkdown(root: File, sources: List<KtSource>): String {
    val projectRef = Regex("project\\(\"(:[^\"]+)\"\\)")

    data class Card(val path: String, val deps: List<String>, val interfaces: List<String>)

    val cards = mutableListOf<Card>()
    for (zone in listOf("capability", "domain")) {
        val dir = File(root, zone)
        if (!dir.isDirectory) continue
        dir.walkTopDown()
            .onEnter { it.name != "build" && it.name != ".gradle" }
            .filter { it.isFile && it.name == "build.gradle.kts" }
            .forEach { f ->
                val rel = f.parentFile.relativeTo(root).invariantSeparatorsPath
                val path = ":" + rel.replace('/', ':')
                val deps = projectRef.findAll(stripComments(f.readText(Charsets.UTF_8)))
                    .map { it.groupValues[1] }
                    .filter { it != path }
                    .distinct()
                    .sortedWith(compareBy { it })
                    .toList()
                val interfaces = sources
                    .filter { it.module == path && it.relPath.contains("/src/commonMain/") }
                    .flatMap { declarations(it) }
                    .filter { it.kind == "interface" && it.topLevel }
                    .map { it.name }
                    .distinct()
                    .sortedWith(compareBy { it })
                cards += Card(path, deps, interfaces)
            }
    }
    cards.sortWith(compareBy { it.path })

    val sb = StringBuilder()
    sb.append("# Feature cards — current-state edition\n")
    sb.append("\n")
    sb.append("Generated by `./gradlew architectureDiagrams` from a directory walk over `domain/` and\n")
    sb.append("`capability/` (today's stand-in for the target `feature/` packages) plus a parse of the\n")
    sb.append("forge factory's preset enum. Do not edit — the `:tools:diagrams` freshness test fails\n")
    sb.append("on drift; regenerate instead.\n")
    sb.append("\n")
    for (card in cards) {
        sb.append("## `").append(card.path).append("`\n")
        sb.append("\n")
        sb.append("- depends on: ")
        sb.append(
            if (card.deps.isEmpty()) "—"
            else card.deps.joinToString(", ") { "`$it`" },
        )
        sb.append("\n")
        sb.append("- interfaces declared (commonMain): ")
        sb.append(
            if (card.interfaces.isEmpty()) "—"
            else card.interfaces.joinToString(", ") { "`$it`" },
        )
        sb.append("\n")
        sb.append("\n")
    }
    sb.append(forgeMapSection(sources))
    return sb.toString()
}

/**
 * The forge name→sources map (`SNAPSYNC_FORGE_STATE`): each preset of the first enum declared in
 * the file that declares `forgeStatusHost`, with the verbatim forged-input arguments.
 */
private fun forgeMapSection(sources: List<KtSource>): String {
    val sb = StringBuilder()
    sb.append("## Forge name→sources map (`SNAPSYNC_FORGE_STATE`)\n")
    sb.append("\n")
    val forgeFile = sources.firstOrNull { Regex("\\bfun\\s+forgeStatusHost\\s*\\(").containsMatchIn(it.stripped) }
    if (forgeFile == null) {
        sb.append("- no `forgeStatusHost` factory found\n")
        return sb.toString()
    }
    sb.append("Declared in `").append(forgeFile.relPath).append("`.\n")
    sb.append("\n")
    sb.append("| State | Forged inputs |\n")
    sb.append("|---|---|\n")
    val text = forgeFile.stripped
    val enumStart = Regex("\\benum\\s+class\\s+\\w+").find(text)
    if (enumStart != null) {
        val bodyOpen = text.indexOf('{', enumStart.range.last)
        val bodyEnd = skipBalanced(text, bodyOpen, '{', '}') - 1
        // Entries end at the `;` (or the body brace) that separates them from the companion.
        val entriesEnd = text.indexOf(';', bodyOpen).let { if (it in (bodyOpen + 1) until bodyEnd) it else bodyEnd }
        val entry = Regex("(?m)^\\s{4}([A-Z][A-Z_0-9]*)\\s*\\(")
        for (m in entry.findAll(text.substring(bodyOpen, entriesEnd))) {
            val argsOpen = bodyOpen + m.range.last
            val argsEnd = skipBalanced(text, argsOpen, '(', ')') - 1
            val args = text.substring(argsOpen + 1, argsEnd).replace(Regex("\\s+"), " ").trim()
            val state = args.substringBefore(',').trim().trim('"')
            val rest = args.substringAfter(',').trim()
            sb.append("| `").append(state).append("` | `").append(rest).append("` |\n")
        }
    }
    return sb.toString()
}
