package app.snapsync.tools.diagrams

/**
 * The flow transcriber, current-state edition: paper-transcription of the app root's OS-trigger
 * bodies. The closed grammar the `architecture-diagrams` spec gates on — straight-line feature
 * calls, `par` fan-out, `when` over a feature-returned sealed result, a single leading guard
 * clause — arms as a GENERATION FAILURE only when the target `flow/` zone exists; until then every
 * construct outside it is emitted as a burn-down item, never a build failure. That asymmetry is
 * deliberate: an untranscribable flow in `flow/` is a law violation, an untranscribable construct
 * in today's `SnapSyncRoot` is the migration's starting line.
 */

/**
 * The OS-trigger surface of the current app root. A fixed list, not a walk, because "which public
 * functions are OS entry points" is a semantic fact the current shell cannot expose mechanically —
 * the target `lifecycle/` zone makes this derivable (one flow per lifecycle function), at which
 * point this list is deleted.
 */
val TRIGGERS: List<String> = listOf(
    "handleBackgroundUrlSession",
    "onBackground",
    "onForeground",
    "onOpenUrl",
    "onPushToken",
    "onSilentPush",
    "provisionEvent",
    "runDownloadBackstop",
)

/** One transcribed call: `receiver.method(args)` at a body's top level. */
private data class Step(val line: Int, val receiver: String, val method: String, val hasArgs: Boolean)

/** One construct outside the closed grammar. */
private data class Gap(val line: Int, val kind: String, val snippet: String)

/** rel-path (under `architecture/flows/`) → rendered markdown, one file per trigger. */
fun flowsMarkdown(sources: List<KtSource>): Map<String, String> {
    val appRoot = sources.single { it.relPath.endsWith("/SnapSyncRoot.kt") }
    return TRIGGERS.associate { trigger ->
        "architecture/flows/$trigger.md" to renderFlow(appRoot, trigger)
    }
}

private fun renderFlow(src: KtSource, trigger: String): String {
    val body = functionBody(src, trigger)
    val (steps, gaps) = if (body == null) emptyList<Step>() to emptyList() else walk(src, body)

    val sb = StringBuilder()
    sb.append("# Flow — `").append(trigger).append("` (current-state paper transcription)\n")
    sb.append("\n")
    sb.append("Generated by `./gradlew architectureDiagrams` from `").append(src.relPath).append("`.\n")
    sb.append("Do not edit — the `:tools:diagrams` freshness test fails on drift; regenerate instead.\n")
    sb.append("\n")
    sb.append("Current-state edition: the closed transcriber grammar (straight-line feature calls,\n")
    sb.append("`par` fan-out, `when` over a feature-returned sealed result, a single leading guard\n")
    sb.append("clause) and its generation-failure gate arm only when the target `flow/` zone exists;\n")
    sb.append("until then each construct outside the grammar is a burn-down item below, not a build\n")
    sb.append("failure. `log.*` statements are diagnostics, not flow, and are omitted from both lists.\n")
    sb.append("\n")
    sb.append("```mermaid\n")
    sb.append("sequenceDiagram\n")
    sb.append("  participant OS\n")
    sb.append("  participant SnapSyncRoot\n")
    val declared = linkedSetOf("OS", "SnapSyncRoot")
    for (step in steps) {
        val receiver = if (step.receiver.isEmpty()) "SnapSyncRoot" else step.receiver
        if (declared.add(receiver)) {
            val id = receiver.replace('.', '_')
            if (id == receiver) {
                sb.append("  participant ").append(receiver).append("\n")
            } else {
                sb.append("  participant ").append(id).append(" as ").append(receiver).append("\n")
            }
        }
    }
    sb.append("  OS->>SnapSyncRoot: ").append(trigger).append("()\n")
    for (step in steps) {
        val receiver = if (step.receiver.isEmpty()) "SnapSyncRoot" else step.receiver
        sb.append("  SnapSyncRoot->>").append(receiver.replace('.', '_')).append(": ")
            .append(step.method).append(if (step.hasArgs) "(…)" else "()").append("\n")
    }
    if (steps.isEmpty()) {
        sb.append("  Note over SnapSyncRoot: no transcribable calls — see burn-down\n")
    }
    sb.append("```\n")
    sb.append("\n")
    sb.append("## Not transcribable (burn-down)\n")
    sb.append("\n")
    if (body == null) {
        sb.append("- the trigger function was not found in the source — the trigger list is stale\n")
    } else if (gaps.isEmpty()) {
        sb.append("- none\n")
    } else {
        for (gap in gaps) {
            sb.append("- line ").append(gap.line).append(" — ").append(gap.kind)
                .append(": `").append(gap.snippet).append("`\n")
        }
    }
    return sb.toString()
}

// ---- body extraction -----------------------------------------------------------------------

private data class Body(val start: Int, val end: Int)

/**
 * The effective body of `fun <name>`: a block body's braces, or — for the house pattern
 * `fun x(…) = log.invocation(…) { body }` — the wrapper's trailing lambda, which the transcriber
 * treats as transparent (the wrapper is diagnostics, not flow).
 */
private fun functionBody(src: KtSource, name: String): Body? {
    val text = src.stripped
    val m = Regex("\\bfun\\s+" + Regex.escape(name) + "\\s*\\(").find(text) ?: return null
    var i = skipBalanced(text, m.range.last, '(', ')')
    i = skipWs(text, i)
    if (i < text.length && text[i] == ':') { // declared return type
        while (i < text.length && text[i] != '=' && text[i] != '{') i++
    }
    if (i >= text.length) return null
    if (text[i] == '{') return Body(i + 1, skipBalanced(text, i, '{', '}') - 1)
    if (text[i] != '=') return null
    i = skipWs(text, i + 1)
    val exprStart = i
    while (i < text.length && (text[i].isLetterOrDigit() || text[i] == '.' || text[i] == '_')) i++
    if (i < text.length && text[i] == '(') {
        i = skipBalanced(text, i, '(', ')')
        i = skipWs(text, i)
        if (i < text.length && text[i] == '{') {
            return Body(i + 1, skipBalanced(text, i, '{', '}') - 1)
        }
    }
    // Any other expression body: a single-statement body ending at the line.
    val eol = text.indexOf('\n', exprStart)
    return Body(exprStart, if (eol < 0) text.length else eol)
}

private fun skipWs(text: String, from: Int): Int {
    var i = from
    while (i < text.length && text[i].isWhitespace()) i++
    return i
}

/** From an opening delimiter at/after [from], return the index just past its balanced close. */
internal fun skipBalanced(text: String, from: Int, open: Char, close: Char): Int {
    var i = text.indexOf(open, from)
    if (i < 0) return text.length
    var depth = 0
    while (i < text.length) {
        when (text[i]) {
            open -> depth++
            close -> {
                depth--
                if (depth == 0) return i + 1
            }
        }
        i++
    }
    return text.length
}

// ---- statement walking ---------------------------------------------------------------------

private val CALL = Regex("^(?:return@\\w+\\s+)?([A-Za-z_][A-Za-z0-9_]*(?:\\.[A-Za-z_][A-Za-z0-9_]*)*)\\((.*)\\)$")

private fun walk(src: KtSource, body: Body): Pair<List<Step>, List<Gap>> {
    val text = src.stripped
    val steps = mutableListOf<Step>()
    val gaps = mutableListOf<Gap>()
    var i = body.start
    while (i < body.end) {
        while (i < body.end && text[i].isWhitespace()) i++
        if (i >= body.end) break
        val stmtStart = i
        var depth = 0
        var blockOpen = -1
        var j = i
        while (j < body.end) {
            when (text[j]) {
                '(' -> depth++
                ')' -> depth--
                '{' -> if (depth == 0) { blockOpen = j; break }
                '\n' -> if (depth == 0) break
            }
            j++
        }
        val line = src.lineOf(stmtStart)
        if (blockOpen >= 0) {
            var k = skipBalanced(text, blockOpen, '{', '}')
            // Chained continuations stay part of THIS statement (else / catch / finally).
            while (true) {
                val t = skipWs(text, k)
                if (t < body.end && (
                        text.startsWith("else", t) ||
                            text.startsWith("catch", t) ||
                            text.startsWith("finally", t)
                        )
                ) {
                    val nextBrace = text.indexOf('{', t)
                    if (nextBrace < 0 || nextBrace >= body.end) break
                    k = skipBalanced(text, nextBrace, '{', '}')
                } else {
                    break
                }
            }
            val head = text.substring(stmtStart, blockOpen).trim().replace(Regex("\\s+"), " ")
            if (!head.startsWith("log.")) {
                gaps += Gap(line, classify(head, hasBlock = true), snippetAt(src, stmtStart))
            }
            i = k
        } else {
            val stmt = text.substring(stmtStart, j).trim().replace(Regex("\\s+"), " ")
            if (stmt.isNotEmpty() && !stmt.startsWith("log.")) {
                val call = CALL.find(stmt)
                if (call != null && !stmt.startsWith("if") && !stmt.startsWith("when") &&
                    !stmt.startsWith("return ")
                ) {
                    val chain = call.groupValues[1]
                    steps += Step(
                        line = line,
                        receiver = chain.substringBeforeLast('.', missingDelimiterValue = ""),
                        method = chain.substringAfterLast('.'),
                        hasArgs = call.groupValues[2].isNotBlank(),
                    )
                } else {
                    gaps += Gap(line, classify(stmt, hasBlock = false), snippetAt(src, stmtStart))
                }
            }
            i = j + 1
        }
    }
    return steps to gaps
}

private fun classify(stmt: String, hasBlock: Boolean): String = when {
    stmt.startsWith("if ") || stmt.startsWith("if(") -> "`if` conditional"
    stmt.startsWith("when ") || stmt.startsWith("when(") || stmt.startsWith("when{") -> "`when`"
    stmt.contains("?.let") -> "`?.let` chain"
    Regex("\\bscope\\s*\\.\\s*launch\\b").containsMatchIn(stmt) -> "`scope.launch` body"
    stmt.contains("runCatching") -> "`runCatching`"
    stmt.startsWith("val ") || stmt.startsWith("var ") ||
        Regex("^[A-Za-z_][\\w.]*\\s*=[^=]").containsMatchIn(stmt) -> "assignment"
    stmt.startsWith("return") -> "early return"
    Regex("^[A-Za-z_][\\w.]*$").matches(stmt) -> "bare property read (lazy-init touch)"
    hasBlock -> "call with lambda body"
    else -> "outside grammar"
}

/** The statement's first source line, verbatim (comment text included), for the burn-down list. */
private fun snippetAt(src: KtSource, offset: Int): String {
    val eol = src.text.indexOf('\n', offset)
    return src.text.substring(offset, if (eol < 0) src.text.length else eol).trim()
}
