package app.snapsync.tools.diagrams

/**
 * The module-graph Mermaid renderer. Only Gradle can see the project model, so the model itself is
 * dumped by the root project's `architectureModulesDiagram` task into the committed sidecar
 * `architecture/.modules-inputs.txt`; this renderer turns that model into `architecture/modules.md`.
 *
 * ⚠ BYTE-IDENTICAL TWIN: the root `build.gradle.kts` carries the same renderer (it must emit
 * `modules.md` without depending on this module's jar). Change BOTH or the freshness test fails —
 * loudly, by design: two renderers disagreeing is drift.
 */

/** `:adapter:ios:ext-safe` → `adapter_ios_ext_safe` (a Mermaid-safe node id). */
fun mermaidId(path: String): String = path.trimStart(':').replace(':', '_').replace('-', '_')

fun renderModulesMarkdown(modules: List<String>, edges: List<Pair<String, String>>): String {
    val sb = StringBuilder()
    sb.append("# Module dependency graph\n")
    sb.append("\n")
    sb.append("Generated by `./gradlew architectureDiagrams` from the Gradle project model: every\n")
    sb.append("`project(...)` dependency declared by any configuration of any module, deduplicated.\n")
    sb.append("Do not edit — the `:tools:diagrams` freshness test fails on drift; regenerate instead.\n")
    sb.append("\n")
    sb.append("```mermaid\n")
    sb.append("flowchart LR\n")
    for (m in modules) sb.append("  ").append(mermaidId(m)).append("[\"").append(m).append("\"]\n")
    for ((from, to) in edges) {
        sb.append("  ").append(mermaidId(from)).append(" --> ").append(mermaidId(to)).append("\n")
    }
    sb.append("```\n")
    return sb.toString()
}

/** Parse the sidecar model dump: `module <path>` and `edge <from> <to>` lines, comments ignored. */
fun parseModulesSidecar(text: String): Pair<List<String>, List<Pair<String, String>>> {
    val modules = mutableListOf<String>()
    val edges = mutableListOf<Pair<String, String>>()
    for (line in text.split("\n")) {
        val parts = line.trim().split(" ")
        when {
            parts.size == 2 && parts[0] == "module" -> modules += parts[1]
            parts.size == 3 && parts[0] == "edge" -> edges += parts[1] to parts[2]
        }
    }
    return modules to edges
}
