package app.snapsync.tools.diagrams

import java.io.File

/**
 * The port × adapter matrix, current-state edition. Heuristics are simple and DERIVED (no hand
 * lists): a `commonMain` interface under `domain/` or `capability/` counts as a port when its own
 * file speaks of a seam/port, or when a `class`/`object` elsewhere implements it. Matching is by
 * simple name — good enough while names are unique, and a collision only ever ADDS a row.
 */
fun portsMarkdown(root: File, sources: List<KtSource>): String {
    val commonMainInterface = Regex("^(domain|capability)/.*/src/commonMain/.*")
    val seamWord = Regex("(?i)\\b(seam|port)s?\\b")

    data class Impl(val name: String, val module: String, val underTest: Boolean)

    // Every class/object implementation, keyed by each supertype's simple name.
    val implsBySupertype = mutableMapOf<String, MutableList<Impl>>()
    for (source in sources) {
        for (decl in declarations(source)) {
            if (decl.kind == "interface") continue
            for (supertype in decl.supertypes) {
                implsBySupertype.getOrPut(supertype) { mutableListOf() } += Impl(
                    name = decl.name,
                    module = source.module ?: "?",
                    underTest = source.relPath.startsWith("test/") ||
                        decl.name.startsWith("Fake") || decl.name.startsWith("InMemory"),
                )
            }
        }
    }

    data class Row(val port: String, val module: String, val impls: List<Impl>)

    val rows = mutableListOf<Row>()
    for (source in sources) {
        if (!commonMainInterface.matches(source.relPath)) continue
        val mentionsSeam = seamWord.containsMatchIn(source.text)
        for (decl in declarations(source)) {
            if (decl.kind != "interface") continue
            val impls = implsBySupertype[decl.name].orEmpty()
            if (!mentionsSeam && impls.isEmpty()) continue
            rows += Row(decl.name, source.module ?: "?", impls)
        }
    }
    rows.sortWith(compareBy({ it.port }, { it.module }))

    val sb = StringBuilder()
    sb.append("# Port × adapter matrix — current-state edition\n")
    sb.append("\n")
    sb.append("Generated by `./gradlew architectureDiagrams` from a source scan (derived scope, no hand\n")
    sb.append("lists): every `commonMain` interface under `domain/` or `capability/` whose file mentions\n")
    sb.append("a seam/port or which has `class … : X` implementations anywhere in the tree. \"Fake\n")
    sb.append("exists\" = an implementation under `test/` or named `Fake*`/`InMemory*`. Do not edit —\n")
    sb.append("the `:tools:diagrams` freshness test fails on drift; regenerate instead.\n")
    sb.append("\n")
    sb.append("| Port | Declared in | Implementations (by module) | Fake exists |\n")
    sb.append("|---|---|---|---|\n")
    for (row in rows) {
        val byModule = row.impls
            .groupBy { it.module }
            .toSortedMap(compareBy { it })
            .entries
            .joinToString("; ") { (module, impls) ->
                "`$module` " + impls.map { it.name }.sortedWith(compareBy { it }).distinct().joinToString(", ")
            }
        val fake = if (row.impls.any { it.underTest }) "yes" else "no"
        sb.append("| `").append(row.port).append("` | `").append(row.module).append("` | ")
            .append(byModule.ifEmpty { "—" }).append(" | ").append(fake).append(" |\n")
    }
    return sb.toString()
}
