package app.snapsync.tools.diagrams

import java.io.File

/**
 * The zone/feature graph, current-state edition: every module under `domain/` and `capability/`
 * (a directory walk, so the scope tracks the migration automatically), with the edges each module
 * declares via `project(...)` in its `build.gradle.kts`. When the target zones (`:domain`
 * packages, `:adapter:*`, `:ui:*`) land, the same walk picks them up and the graph reshapes itself.
 */
fun zonesMarkdown(root: File): String {
    val zones = listOf("adapter", "capability", "domain")
    // path → declared project() targets
    val moduleEdges = sortedMapOf<String, List<String>>(compareBy { it })
    val projectRef = Regex("project\\(\"(:[^\"]+)\"\\)")
    for (zone in zones) {
        val dir = File(root, zone)
        if (!dir.isDirectory) continue
        dir.walkTopDown()
            .onEnter { it.name != "build" && it.name != ".gradle" }
            .filter { it.isFile && it.name == "build.gradle.kts" }
            .forEach { f ->
                val rel = f.parentFile.relativeTo(root).invariantSeparatorsPath
                val path = ":" + rel.replace('/', ':')
                val script = stripComments(f.readText(Charsets.UTF_8))
                moduleEdges[path] = projectRef.findAll(script)
                    .map { it.groupValues[1] }
                    .filter { it != path }
                    .distinct()
                    .sortedWith(compareBy { it })
                    .toList()
            }
    }
    // Nodes grouped by zone (first path segment); edge targets outside the walked zones still get
    // a node so no declared edge dangles.
    val nodes = (moduleEdges.keys + moduleEdges.values.flatten())
        .toSortedSet(compareBy { it })
    val groups = nodes.groupBy { it.trimStart(':').substringBefore(':') }
        .toSortedMap(compareBy { it })

    val sb = StringBuilder()
    sb.append("# Zone / feature graph — current-state edition\n")
    sb.append("\n")
    sb.append("Generated by `./gradlew architectureDiagrams` from the `project(...)` declarations in\n")
    sb.append("every `build.gradle.kts` under `adapter/`, `domain/` and `capability/` (a directory walk —\n")
    sb.append("the scope\n")
    sb.append("is derived, so this graph tracks the migration automatically as modules move). Do not\n")
    sb.append("edit — the `:tools:diagrams` freshness test fails on drift; regenerate instead.\n")
    sb.append("\n")
    sb.append("```mermaid\n")
    sb.append("flowchart LR\n")
    for ((zone, members) in groups) {
        sb.append("  subgraph ").append(zone).append("\n")
        for (m in members.sortedWith(compareBy { it })) {
            sb.append("    ").append(mermaidId(m)).append("[\"").append(m).append("\"]\n")
        }
        sb.append("  end\n")
    }
    for ((from, targets) in moduleEdges) {
        for (to in targets) {
            sb.append("  ").append(mermaidId(from)).append(" --> ").append(mermaidId(to)).append("\n")
        }
    }
    sb.append("```\n")
    return sb.toString()
}
