package app.snapsync.config

import platform.Foundation.NSBundle
import platform.Foundation.NSDictionary
import platform.Foundation.dictionaryWithContentsOfFile

/**
 * The resolved deployment's device-facing values, read from this process's OWN bundle (capability
 * `deployment-configuration`).
 *
 * `Deployment.plist` is GENERATED by `scripts/resolve-deployment.py` and copied into **both** bundles —
 * the app and the background-upload extension — because each process reads its own `NSBundle.mainBundle`.
 * A copy that reached only one of them is a reachable state, which is why `ios.yml` asserts the file and
 * its values against both bundles rather than against the generator's output.
 *
 * **Why a plist and not the xcconfig fragment.** `//` opens a comment anywhere on an xcconfig line and
 * that grammar offers no escape, so a value carrying a scheme is truncated silently. The crash-reporting
 * DSN became `https:` — non-empty, so the SDK never started while the in-app bug-report dialog kept
 * opening and losing every dump, and four TestFlight builds shipped mute. A property list escapes. The
 * xcconfig now carries only build settings and entitlement inputs, all sourced from reviewed literals.
 *
 * Read once and cached: the file cannot change under a running process, so this is a derived cache of an
 * immutable fact rather than state. The absence collapses are NOT uniform and must not be made so — each
 * caller below names the consequence that makes its own default safe, and one of them deliberately
 * answers "couldn't tell" rather than naming a value.
 */
fun deploymentValue(key: String): String? = deploymentValues[key]?.takeIf { it.isNotBlank() }

private val deploymentValues: Map<String, String> by lazy {
    val path = NSBundle.mainBundle.pathForResource("Deployment", ofType = "plist") ?: return@lazy emptyMap()
    val contents = NSDictionary.dictionaryWithContentsOfFile(path) ?: return@lazy emptyMap()
    contents.entries.mapNotNull { entry ->
        val name = entry.key as? String ?: return@mapNotNull null
        val value = entry.value as? String ?: return@mapNotNull null
        name to value
    }.toMap()
}

/**
 * The compile-time APNs environment this build registers (`sandbox` | `production`, capability
 * `push-registration`), reported in `devices/<id>/config.json` so the backend picks the right APNs host
 * per token. Derived from the same build-channel discriminant as the `aps-environment` entitlement, so
 * the two cannot disagree.
 *
 * `sandbox` when absent — the safe end of the pair: a sandbox token rejected by production APNs fails
 * loudly at registration, where a production token accepted for a sandbox build would silently never
 * deliver. Lives here rather than in `:app:ios` for the reason [bakedUploadBase] does: the shell is
 * gated to hold no decisions, and choosing what an absent key becomes is one.
 */
fun bakedApnsEnv(): String = deploymentValue("apnsEnv") ?: "sandbox"

/**
 * The crash-reporting ingestion key, or `null` when this build carries none — which is every
 * dev/sideload build. **Absence is the off-switch** (capability `crash-reporting`): the renderer emits
 * no DSN unless the build channel names a distributed build, so the SDK never starts and no connection
 * to the reporting host is ever opened.
 */
fun bakedSentryDsn(): String? = deploymentValue("sentryDsn")

/**
 * The environment crash reports are filed under. `development` when absent, so a build that somehow
 * carries a DSN without an environment reports honestly rather than claiming production.
 */
fun bakedSentryEnvironment(): String = deploymentValue("sentryEnvironment") ?: "development"
